import { createClient } from "@supabase/supabase-js";
import { serviceLineBoardTagColors } from "../../../lib/serviceLineBoards";

function configuredSupabase(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Supabase server configuration is missing.");return createClient(url,key,{auth:{persistSession:false}});}
function clean(value:unknown){return String(value??"").trim();}
function key(value:unknown){return clean(value).toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}
function validUuid(value:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);}
function errorMessage(error:unknown){return error instanceof Error?error.message:String((error as {message?:unknown})?.message??error);}
function missing(error:unknown){const message=key(errorMessage(error));return message.includes("titan inspectors")||message.includes("titan training gaps")||message.includes("schema cache");}

async function authorize(request:Request,admin:ReturnType<typeof configuredSupabase>){const token=(request.headers.get("authorization")??"").replace(/^Bearer\s+/i,"").trim();if(!token)return{error:Response.json({error:"You must be signed in."},{status:401})};const{data:userData,error}=await admin.auth.getUser(token);if(error||!userData.user)return{error:Response.json({error:"Your session could not be verified."},{status:401})};const{data:profile}=await admin.from("profiles").select("role,is_disabled").eq("id",userData.user.id).maybeSingle();if(!profile||profile.is_disabled||["customer","operator"].includes(key(profile.role)))return{error:Response.json({error:"Crew readiness is available to internal TITAN users."},{status:403})};return{userId:userData.user.id};}

const employeeTags=new Set(Object.keys(serviceLineBoardTagColors).filter(tag=>tag!=="Safety Hours"));
function categoryFrom(value:unknown){const text=clean(value);const cat=text.match(/\bcat(?:egory)?\s*([1-5])\b/i);if(cat)return`Cat ${cat[1]}`;return/\bhdls\b/i.test(text)?"HDLS":"";}
function isSpecialLane(value:unknown){return /bullpen|off schedule|suspended|safety hours|terminated|truck|trailer/i.test(clean(value));}

async function loadBoardReadiness(admin:ReturnType<typeof configuredSupabase>,boardId:string){
  const [columnsResult,cardsResult,profilesResult,inspectorsResult,qualificationsResult,gapsResult]=await Promise.all([
    admin.from("service_board_columns").select("id,title,column_key").eq("board_id",boardId).eq("active",true),
    admin.from("service_board_cards").select("id,column_id,title,tags,source_type,source_id,archived_at").eq("board_id",boardId).is("archived_at",null),
    admin.from("profiles").select("id,full_name,is_disabled").eq("is_disabled",false),
    admin.from("titan_inspectors").select("id,profile_id,iom_level,field_score,status").eq("status","Active"),
    admin.from("titan_ds1_qualifications").select("inspector_id,category,qualification_status").eq("is_current",true),
    admin.from("titan_training_gaps").select("inspector_id,priority,gap_text,scope_category,gap_status,due_date").in("gap_status",["Planned","In Progress"]),
  ]);
  for(const result of[columnsResult,cardsResult,profilesResult,inspectorsResult,qualificationsResult,gapsResult])if(result.error)throw result.error;
  const columns=columnsResult.data??[];const cards=cardsResult.data??[];const profiles=(profilesResult.data??[]).sort((a,b)=>clean(b.full_name).length-clean(a.full_name).length);const inspectors=inspectorsResult.data??[];const qualifications=qualificationsResult.data??[];const gaps=gapsResult.data??[];
  const jobCards=cards.filter(card=>card.source_type==="titan_job"&&validUuid(clean(card.source_id)));const jobIds=[...new Set(jobCards.map(card=>clean(card.source_id)))];
  const jobsResult=jobIds.length?await admin.from("titan_jobs").select("id,job_number,title,job_type,job_description").in("id",jobIds):{data:[],error:null};if(jobsResult.error)throw jobsResult.error;const jobs=jobsResult.data??[];
  const categoryByColumn=new Map<string,string>();jobCards.forEach(card=>{const job=jobs.find(row=>row.id===card.source_id);const category=categoryFrom(`${job?.job_type??""} ${job?.job_description??""}`);if(category)categoryByColumn.set(card.column_id,category);});columns.forEach(column=>{if(!categoryByColumn.has(column.id)){const category=categoryFrom(column.title);if(category)categoryByColumn.set(column.id,category);}});
  const employeeCards=cards.filter(card=>(card.tags??[]).some((tag:string)=>employeeTags.has(tag)));
  function matchProfile(title:string){const titleKey=key(title);return profiles.find(profile=>{const nameKey=key(profile.full_name);return titleKey===nameKey||titleKey.startsWith(`${nameKey} `);})??null;}
  function evaluate(card:(typeof employeeCards)[number],columnId:string){const column=columns.find(row=>row.id===columnId);if(!column||isSpecialLane(column.title))return{cardId:card.id,columnId,status:"not_applicable",label:"Not scheduled",reason:"This is not an active job lane.",profileId:null,inspectorId:null,fieldScore:null,category:""};const profile=matchProfile(card.title);if(!profile)return{cardId:card.id,columnId,status:"unlinked",label:"Profile not linked",reason:"Match this employee card to a TITAN employee profile before checking readiness.",profileId:null,inspectorId:null,fieldScore:null,category:categoryByColumn.get(columnId)||""};const inspector=inspectors.find(row=>row.profile_id===profile.id);if(!inspector)return{cardId:card.id,columnId,status:"not_in_matrix",label:"Matrix not set",reason:`${profile.full_name} has not been added to HR-CM-001.`,profileId:profile.id,inspectorId:null,fieldScore:null,category:categoryByColumn.get(columnId)||""};const category=categoryByColumn.get(columnId)||"";const qualification=category?qualifications.find(row=>row.inspector_id===inspector.id&&row.category===category):null;const blockingGaps=gaps.filter(row=>row.inspector_id===inspector.id&&row.priority==="High"&&(!row.scope_category||!category||key(row.scope_category)===key(category)));if(blockingGaps.length)return{cardId:card.id,columnId,status:"blocked",label:"High gap",reason:`${profile.full_name} has an open high-priority gap: ${blockingGaps[0].gap_text}`,profileId:profile.id,inspectorId:inspector.id,fieldScore:inspector.field_score,category};if(category&&(!qualification||!["Qualified","Lead Qualified"].includes(qualification.qualification_status)))return{cardId:card.id,columnId,status:"blocked",label:`Not qualified: ${category}`,reason:`${profile.full_name} is not currently qualified for ${category}.`,profileId:profile.id,inspectorId:inspector.id,fieldScore:inspector.field_score,category};if(Number(inspector.field_score??0)<80)return{cardId:card.id,columnId,status:"watch",label:`Developing ${Number(inspector.field_score??0).toFixed(0)}%`,reason:`${profile.full_name}'s field score is below the 80% readiness target.`,profileId:profile.id,inspectorId:inspector.id,fieldScore:inspector.field_score,category};return{cardId:card.id,columnId,status:"ready",label:`Ready ${Number(inspector.field_score).toFixed(0)}%`,reason:`${profile.full_name} meets the current competency check.`,profileId:profile.id,inspectorId:inspector.id,fieldScore:inspector.field_score,category};}
  const cardReadiness=employeeCards.map(card=>evaluate(card,card.column_id));const laneReadiness=columns.map(column=>{const people=employeeCards.filter(card=>card.column_id===column.id);const results=people.map(card=>evaluate(card,column.id));const category=categoryByColumn.get(column.id)||"";const inspectorIds=results.map(row=>row.inspectorId).filter(Boolean);const hasLeadQualified=!category||qualifications.some(row=>inspectorIds.includes(row.inspector_id)&&row.category===category&&row.qualification_status==="Lead Qualified");const issues=results.filter(row=>["blocked","watch","unlinked","not_in_matrix"].includes(row.status)).length+(!hasLeadQualified&&people.length?1:0);return{columnId:column.id,category,people:people.length,issues,hasLeadQualified,status:issues?"attention":people.length?"ready":"empty"};});
  return{cardReadiness,laneReadiness,evaluate,cards:employeeCards};
}

export async function GET(request:Request){try{const admin=configuredSupabase();const auth=await authorize(request,admin);if("error"in auth)return auth.error;const boardId=clean(new URL(request.url).searchParams.get("boardId"));if(!validUuid(boardId))return Response.json({error:"Select a valid service board."},{status:400});const result=await loadBoardReadiness(admin,boardId);return Response.json({ok:true,cardReadiness:result.cardReadiness,laneReadiness:result.laneReadiness});}catch(error){return Response.json({error:missing(error)?"Run supabase/titan_competency_matrix.sql to activate crew readiness.":errorMessage(error)},{status:missing(error)?409:500});}}

export async function POST(request:Request){try{const admin=configuredSupabase();const auth=await authorize(request,admin);if("error"in auth)return auth.error;const body=await request.json().catch(()=>({})) as Record<string,unknown>;const boardId=clean(body.boardId),cardId=clean(body.cardId),columnId=clean(body.columnId);if(![boardId,cardId,columnId].every(validUuid))return Response.json({error:"A valid board, employee card, and destination lane are required."},{status:400});const result=await loadBoardReadiness(admin,boardId);const card=result.cards.find(row=>row.id===cardId);if(!card)return Response.json({ok:true,requiresConfirmation:false,readiness:null});const readiness=result.evaluate(card,columnId);return Response.json({ok:true,requiresConfirmation:["blocked","watch","unlinked","not_in_matrix"].includes(readiness.status),readiness});}catch(error){return Response.json({error:missing(error)?"Run supabase/titan_competency_matrix.sql to activate crew readiness.":errorMessage(error)},{status:missing(error)?409:500});}}
