"use client";

import Image from "next/image";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { dtiInspectionCategoryOptions, dtiInspectionFields, dtiRefaceOptions, normalizeDtiRefaceCode, normalizeDtiRefaceRowData, resolveDtiReportComponentType, summarizeDtiInspection, type DtiComponentType } from "../../../../lib/dtiInspectionReport";
import { flushDtiMutationQueue, getDtiOfflineSnapshot, getQueuedDtiMutations, removeQueuedDtiMutation, saveDtiOfflineSnapshot, sendOrQueueDtiMutation, subscribeToDtiQueue, type DtiQueuedMutation } from "../../../../lib/dtiOfflineQueue";
import { goBackOrFallback } from "../../../../lib/navigation";
import { supabase } from "../../../../lib/supabase";
import DtiInspectionPrintView from "./DtiInspectionPrintView";
import styles from "../reports.module.css";

type Report = { id: string; report_number: string; operator_name: string; contractor_name: string | null; rig_number: string | null; report_date: string; field_invoice: string | null; inspection_crew: string | null; connection_size: string | null; connection_type: string | null; grade: string | null; state: string | null; inspection_scope: Record<string, unknown>; machine_shop: Record<string, unknown>; remarks: Record<string, unknown>; status: string };
type Item = { id: string; report_id: string; component_type: DtiComponentType; sequence_number: number; row_data: Record<string, unknown>; pendingMutationId?: string };
type ProveUp = { id: string; sequence_number: number; joint_number: string | null; serial_number: string | null; flaw: string | null; depth_inches: number | null; adjacent_wall_inches: number | null; remaining_body_wall_inches: number | null; distance_from_end: string | null; prove_up_result: string | null; pendingMutationId?: string };
type ApiData = { ok?: boolean; report?: Report; items?: Item[]; proveUps?: ProveUp[]; error?: string };
type Tab = DtiComponentType | "EMI Prove-Up";
const endpoint = "/api/dti/inspection-reports";
const blankProveUp = { proveUpId: "", sequenceNumber: "1", jointNumber: "", serialNumber: "", flaw: "", depthInches: "", adjacentWallInches: "", remainingBodyWallInches: "", distanceFromEnd: "", proveUpResult: "" };

function reportForm(report: Report) { return { operatorName: report.operator_name || "", contractorName: report.contractor_name || "", rigNumber: report.rig_number || "", reportDate: report.report_date || "", fieldInvoice: report.field_invoice || "", inspectionCrew: report.inspection_crew || "", connectionSize: report.connection_size || "", connectionType: report.connection_type || "", grade: report.grade || "", state: report.state || "", status: report.status || "Draft", inspectionScope: report.inspection_scope || {}, machineShop: report.machine_shop || {}, remarks: report.remarks || {} }; }
function displayValue(value: unknown) { if (value === true) return "X"; if (value === false || value === null || value === undefined || value === "") return "-"; return String(value); }
function objectValue(source: Record<string, unknown>, key: string) { return String(source[key] ?? ""); }

export default function DtiInspectionReportEditor() {
  const params = useParams<{ reportId: string }>(); const reportId = String(params.reportId ?? ""); const snapshotKey = `inspection-report:${reportId}`;
  const [data, setData] = useState<ApiData | null>(null); const [tab, setTab] = useState<Tab>("Drill Pipe"); const [message, setMessage] = useState("Loading inspection report..."); const [online, setOnline] = useState(true); const [pending, setPending] = useState<DtiQueuedMutation[]>([]); const [syncing, setSyncing] = useState(false); const [exporting, setExporting] = useState(false); const [headerOpen, setHeaderOpen] = useState(false); const [header, setHeader] = useState<ReturnType<typeof reportForm> | null>(null); const [itemOpen, setItemOpen] = useState(false); const [itemId, setItemId] = useState(""); const [sequenceNumber, setSequenceNumber] = useState("1"); const [rowData, setRowData] = useState<Record<string, unknown>>({}); const [proveUpOpen, setProveUpOpen] = useState(false); const [proveUp, setProveUp] = useState(blankProveUp);
  const syncingRef = useRef(false);

  const loadPending = useCallback(async () => setPending((await getQueuedDtiMutations(reportId)).filter((item) => item.endpoint === endpoint)), [reportId]);
  const load = useCallback(async () => { try { const { data: auth } = await supabase.auth.getSession(); const token = auth.session?.access_token; if (!token) { const cached = await getDtiOfflineSnapshot<ApiData>(snapshotKey); if (cached && !navigator.onLine) { setData(cached.data); setTab(resolveDtiReportComponentType(cached.data.report?.inspection_scope, cached.data.items)); setHeader(cached.data.report ? reportForm(cached.data.report) : null); setMessage("Offline report copy loaded."); return; } return window.location.assign("/login"); } const request = await fetch(`${endpoint}?reportId=${encodeURIComponent(reportId)}`, { headers: { Authorization: `Bearer ${token}` } }); const body = await request.json() as ApiData; if (!request.ok) throw new Error(body.error || "TITAN could not load this report."); setData(body); setTab(resolveDtiReportComponentType(body.report?.inspection_scope, body.items)); if (body.report) setHeader(reportForm(body.report)); setMessage(""); await saveDtiOfflineSnapshot(snapshotKey, body).catch(() => undefined); } catch (error) { const cached = await getDtiOfflineSnapshot<ApiData>(snapshotKey).catch(() => null); if (cached) { setData(cached.data); setTab(resolveDtiReportComponentType(cached.data.report?.inspection_scope, cached.data.items)); if (cached.data.report) setHeader(reportForm(cached.data.report)); setMessage("Offline report copy loaded. Changes will sync when service returns."); } else setMessage(error instanceof Error ? error.message : "TITAN could not load this report."); } }, [reportId, snapshotKey]);
  const sync = useCallback(async () => { if (syncingRef.current || !navigator.onLine) return; syncingRef.current = true; setSyncing(true); try { const result = await flushDtiMutationQueue(reportId); await loadPending(); if (result.synced) { setMessage(`${result.synced} offline change${result.synced === 1 ? "" : "s"} synced.`); await load(); } } finally { syncingRef.current = false; setSyncing(false); } }, [load, loadPending, reportId]);
  useEffect(() => { const timer = window.setTimeout(() => { setOnline(navigator.onLine); void load(); void loadPending(); }, 0); const unsubscribe = subscribeToDtiQueue(() => void loadPending()); const onOnline = () => { setOnline(true); void sync(); }; const onOffline = () => setOnline(false); window.addEventListener("online", onOnline); window.addEventListener("offline", onOffline); return () => { window.clearTimeout(timer); unsubscribe(); window.removeEventListener("online", onOnline); window.removeEventListener("offline", onOffline); }; }, [load, loadPending, sync]);

  const serverItems = data?.items ?? []; const serverProveUps = data?.proveUps ?? []; const reportComponentType = resolveDtiReportComponentType(data?.report?.inspection_scope, serverItems);
  const pendingItems = useMemo(() => pending.filter((entry) => entry.action === "save-item").map((entry) => ({ id: String(entry.payload.itemId || `pending-${entry.id}`), report_id: reportId, component_type: String(entry.payload.componentType) as DtiComponentType, sequence_number: Number(entry.payload.sequenceNumber), row_data: (entry.payload.rowData ?? {}) as Record<string, unknown>, pendingMutationId: entry.id })), [pending, reportId]);
  const pendingItemIds = useMemo(() => new Set(pendingItems.filter((item) => !item.id.startsWith("pending-")).map((item) => item.id)), [pendingItems]);
  const deletedItemIds = useMemo(() => new Set(pending.filter((entry) => entry.action === "delete-item").map((entry) => String(entry.payload.itemId))), [pending]);
  const allItems = [...pendingItems, ...serverItems.filter((item) => !pendingItemIds.has(item.id) && !deletedItemIds.has(item.id))];
  const items = allItems.filter((item) => item.component_type === tab).sort((a, b) => a.sequence_number - b.sequence_number);
  const pendingProveUps = useMemo(() => pending.filter((entry) => entry.action === "save-prove-up").map((entry) => ({ id: String(entry.payload.proveUpId || `pending-${entry.id}`), sequence_number: Number(entry.payload.sequenceNumber), joint_number: String(entry.payload.jointNumber || ""), serial_number: String(entry.payload.serialNumber || ""), flaw: String(entry.payload.flaw || ""), depth_inches: Number(entry.payload.depthInches) || null, adjacent_wall_inches: Number(entry.payload.adjacentWallInches) || null, remaining_body_wall_inches: Number(entry.payload.remainingBodyWallInches) || null, distance_from_end: String(entry.payload.distanceFromEnd || ""), prove_up_result: String(entry.payload.proveUpResult || ""), pendingMutationId: entry.id })), [pending]);
  const pendingProveUpIds = useMemo(() => new Set(pendingProveUps.filter((item) => !item.id.startsWith("pending-")).map((item) => item.id)), [pendingProveUps]);
  const deletedProveUpIds = useMemo(() => new Set(pending.filter((entry) => entry.action === "delete-prove-up").map((entry) => String(entry.payload.proveUpId))), [pending]);
  const proveUps = [...pendingProveUps, ...serverProveUps.filter((item) => !pendingProveUpIds.has(item.id) && !deletedProveUpIds.has(item.id))].sort((a, b) => a.sequence_number - b.sequence_number);

  async function saveAction(payload: Record<string, unknown>) { const result = await sendOrQueueDtiMutation<ApiData>({ ...payload, reportId }, endpoint); if (result.status === "saved") { setData(result.data); if (result.data.report) setHeader(reportForm(result.data.report)); await saveDtiOfflineSnapshot(snapshotKey, result.data).catch(() => undefined); setMessage("Report saved."); } else { await loadPending(); setMessage("Change saved on this device and queued for sync."); } return result; }
  function addItem() { const next = Math.max(0, ...items.map((item) => item.sequence_number)) + 1; setItemId(""); setSequenceNumber(String(next)); setRowData({ jointNumber: String(next) }); setItemOpen(true); }
  function editItem(item: Item) { setItemId(item.id); setSequenceNumber(String(item.sequence_number)); setRowData(normalizeDtiRefaceRowData(item.row_data)); setItemOpen(true); }
  async function saveItem() { if (tab === "EMI Prove-Up") return; if (itemId.startsWith("pending-")) await removeQueuedDtiMutation(itemId.slice(8)); await saveAction({ action: "save-item", itemId: itemId.startsWith("pending-") ? "" : itemId, componentType: tab, sequenceNumber, rowData: normalizeDtiRefaceRowData(rowData) }); setItemOpen(false); }
  async function deleteItem(item: Item) { if (!window.confirm(`Delete ${item.component_type} row ${item.sequence_number}?`)) return; if (item.pendingMutationId) { await removeQueuedDtiMutation(item.pendingMutationId); setMessage("Pending row removed from this device."); } else await saveAction({ action: "delete-item", itemId: item.id }); }
  function addProveUp() { const next = Math.max(0, ...proveUps.map((item) => item.sequence_number)) + 1; setProveUp({ ...blankProveUp, sequenceNumber: String(next) }); setProveUpOpen(true); }
  function editProveUp(item: ProveUp) { setProveUp({ proveUpId: item.id, sequenceNumber: String(item.sequence_number), jointNumber: item.joint_number || "", serialNumber: item.serial_number || "", flaw: item.flaw || "", depthInches: item.depth_inches === null ? "" : String(item.depth_inches), adjacentWallInches: item.adjacent_wall_inches === null ? "" : String(item.adjacent_wall_inches), remainingBodyWallInches: item.remaining_body_wall_inches === null ? "" : String(item.remaining_body_wall_inches), distanceFromEnd: item.distance_from_end || "", proveUpResult: item.prove_up_result || "" }); setProveUpOpen(true); }
  async function saveProveUp() { if (proveUp.proveUpId.startsWith("pending-")) await removeQueuedDtiMutation(proveUp.proveUpId.slice(8)); await saveAction({ action: "save-prove-up", ...proveUp, proveUpId: proveUp.proveUpId.startsWith("pending-") ? "" : proveUp.proveUpId }); setProveUpOpen(false); }
  async function deleteProveUp(item: ProveUp) { if (!window.confirm(`Delete EMI prove-up row ${item.sequence_number}?`)) return; if (item.pendingMutationId) { await removeQueuedDtiMutation(item.pendingMutationId); setMessage("Pending prove-up removed from this device."); } else await saveAction({ action: "delete-prove-up", proveUpId: item.id }); }
  async function exportOriginalWorkbook() {
    if (pending.length) { setMessage("Sync pending changes before exporting the original workbook."); return; }
    setExporting(true);
    try {
      const { data: auth } = await supabase.auth.getSession(); const token = auth.session?.access_token;
      if (!token) throw new Error("Sign in again before exporting the report.");
      const request = await fetch(`${endpoint}/export?reportId=${encodeURIComponent(reportId)}`, { headers: { Authorization: `Bearer ${token}` } });
      if (!request.ok) { const body = await request.json().catch(() => ({})) as { error?: string }; throw new Error(body.error || "TITAN could not export the original workbook."); }
      const blob = await request.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a");
      anchor.href = url; anchor.download = `${report?.report_number || "DTI-Inspection-Report"}.xlsx`; document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url);
      setMessage("Original Excel report exported.");
    } catch (error) { setMessage(error instanceof Error ? error.message : "TITAN could not export the original workbook."); }
    finally { setExporting(false); }
  }
  const fields = tab === "EMI Prove-Up" ? [] : dtiInspectionFields[tab]; const groups = [...new Set(fields.map((item) => item.group))]; const report = data?.report;
  const componentItems = tab === "EMI Prove-Up" ? [] : allItems.filter((item) => item.component_type === tab);
  const summary = summarizeDtiInspection(componentItems, reportComponentType);
  const scopePrefix = reportComponentType === "Drill Pipe" ? "drillPipe" : reportComponentType === "HWDP" ? "hwdp" : "subs";
  const reportTabs: Tab[] = [reportComponentType, "EMI Prove-Up"];
  const summaryEntries: Array<readonly [string, number]> = [['Inspected',summary.inspected],['Premium',summary.premium],['Rig Ready',summary.rigReady],['Machine Shop',summary.machineShop],['DBR',summary.dbr],['Box Refaces',summary.boxRefaces],['Pin Refaces',summary.pinRefaces],['Hardbands',summary.hardbands],['Damaged Hardbands',summary.damagedHardbands],['DBR Hardbands',summary.dbrHardbands]];
  if (reportComponentType === "HWDP") summaryEntries.push(['Center Pad 1',summary.centerPad1],['Center Pad 2',summary.centerPad2]);

  return <main className={styles.page}>
    <div className={styles.screenOnly}>
    <header className={`${styles.header} titan-page-header`}><div className={styles.title}><Image src="/titan_logo.jpg" alt="TITAN" width={64} height={42} priority /><div><span>{report?.report_number || "DTI Inspection"}</span><h1>{reportComponentType} Inspection Report</h1></div></div><div className={styles.actions}><button type="button" onClick={() => goBackOrFallback("/dti/inspection-reports")}>Back</button><button type="button" onClick={() => void load()}>Refresh</button><button type="button" onClick={() => window.location.assign(`/dti/inspection-reports/${encodeURIComponent(reportId)}/print`)}>Print Preview</button><button type="button" onClick={() => void exportOriginalWorkbook()} disabled={exporting}>{exporting ? "Exporting" : "Export Excel"}</button><button type="button" onClick={() => setHeaderOpen((value) => !value)}>Report Setup</button></div></header>
    <section className={styles.syncBar} data-online={online}><div><span>{online ? "Online" : "Offline"}</span><strong>{pending.length ? `${pending.length} change${pending.length === 1 ? "" : "s"} waiting to sync` : "All changes synced"}</strong></div>{online && pending.length ? <button type="button" onClick={() => void sync()} disabled={syncing}>{syncing ? "Syncing" : "Sync Now"}</button> : null}</section>
    {message ? <div className={message.includes("saved") || message.includes("synced") ? styles.saved : styles.message}>{message}</div> : null}
    {report ? <section className={styles.reportBand}><div><span>Report Type</span><strong>{reportComponentType}</strong></div><div><span>Operator</span><strong>{report.operator_name}</strong></div><div><span>Contractor / Rig</span><strong>{report.contractor_name || "-"} / {report.rig_number || "-"}</strong></div><div><span>Connection</span><strong>{report.connection_size || "-"} / {report.connection_type || "-"}</strong></div><div><span>Status</span><strong>{report.status}</strong></div></section> : null}
    {headerOpen && header ? <section className={styles.editor}><div className={styles.sectionHead}><div><span>Report Header</span><h2>Job and Scope</h2></div><button type="button" onClick={() => setHeaderOpen(false)}>Close</button></div><div className={styles.formGrid}>{([['operatorName','Operator'],['contractorName','Contractor'],['rigNumber','Rig Number'],['reportDate','Date'],['fieldInvoice','Field Invoice'],['inspectionCrew','Inspection Crew'],['connectionSize','Connection Size'],['connectionType','Connection Type'],['grade','Grade'],['state','State']] as const).map(([key,label]) => <label key={key}><span>{label}</span><input type={key === "reportDate" ? "date" : "text"} value={String(header[key] ?? "")} onChange={(event) => setHeader({ ...header, [key]: event.target.value })} /></label>)}<label><span>Status</span><select value={header.status} onChange={(event) => setHeader({ ...header, status: event.target.value })}><option>Draft</option><option>In Progress</option><option>Complete</option></select></label></div>
      <div className={styles.setupSections}><fieldset><legend>{reportComponentType} Inspection</legend><div className={styles.scopeGrid}><label><span>Category</span><select value={objectValue(header.inspectionScope, `${scopePrefix}Category`)} onChange={(event) => setHeader({ ...header, inspectionScope: { ...header.inspectionScope, [`${scopePrefix}Category`]: event.target.value } })}><option value="">None</option>{dtiInspectionCategoryOptions.map((option) => <option key={option}>{option}</option>)}</select></label><label><span>Additional 1</span><input value={objectValue(header.inspectionScope, `${scopePrefix}Additional1`)} onChange={(event) => setHeader({ ...header, inspectionScope: { ...header.inspectionScope, [`${scopePrefix}Additional1`]: event.target.value } })} /></label><label><span>Additional 2</span><input value={objectValue(header.inspectionScope, `${scopePrefix}Additional2`)} onChange={(event) => setHeader({ ...header, inspectionScope: { ...header.inspectionScope, [`${scopePrefix}Additional2`]: event.target.value } })} /></label><label><span>Remarks</span><textarea value={objectValue(header.remarks, scopePrefix)} onChange={(event) => setHeader({ ...header, remarks: { ...header.remarks, [scopePrefix]: event.target.value } })} /></label></div></fieldset></div>
      <fieldset className={styles.setupFieldset}><legend>Machine Shop</legend><div className={styles.formGrid}>{([['name','Name'],['address','Address'],['contact','Contact'],['phone','Phone']] as const).map(([key,label]) => <label key={key}><span>{label}</span><input value={objectValue(header.machineShop, key)} onChange={(event) => setHeader({ ...header, machineShop: { ...header.machineShop, [key]: event.target.value } })} /></label>)}</div></fieldset>
      <div className={styles.editorActions}><button className={styles.primary} type="button" onClick={() => void saveAction({ action: "save-report", ...header })}>Save Setup</button></div>
    </section> : null}
    <nav className={styles.tabs}>{reportTabs.map((value) => <button key={value} type="button" data-active={tab === value} onClick={() => { setTab(value); setItemOpen(false); setProveUpOpen(false); }}>{value}<small>{value === "EMI Prove-Up" ? proveUps.length : allItems.filter((item) => item.component_type === value).length}</small></button>)}</nav>
    {tab !== "EMI Prove-Up" ? <><section className={styles.summaryPanel}><div className={styles.sectionHead}><div><span>{objectValue(report?.inspection_scope ?? {}, `${scopePrefix}Category`) || "Inspection Summary"}</span><h2>{reportComponentType} Totals</h2></div></div><div className={styles.summaryGrid}>{summaryEntries.map(([label,value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></section><section className={styles.inspectionSection}><div className={styles.sectionHead}><div><span>{reportComponentType}</span><h2>Inspection Rows</h2></div><button className={styles.primary} type="button" onClick={addItem}>Add Row</button></div>
      {itemOpen ? <div className={styles.rowEditor}><div className={styles.rowEditorHead}><strong>{itemId ? `Edit Row ${sequenceNumber}` : `New Row ${sequenceNumber}`}</strong><button type="button" onClick={() => setItemOpen(false)}>Close</button></div><datalist id="dti-reface-codes">{dtiRefaceOptions.map((option) => <option key={option.value} value={option.value} />)}</datalist>{groups.map((group) => <fieldset key={group}><legend>{group}</legend><div className={styles.fieldGrid}>{fields.filter((item) => item.group === group).map((field) => <label key={field.key} data-kind={field.kind}><span>{field.label}{field.end ? ` / ${field.end}` : ""}</span>{field.kind === "flag" ? <input type="checkbox" checked={rowData[field.key] === true} onChange={(event) => setRowData({ ...rowData, [field.key]: event.target.checked })} /> : field.kind === "reface" ? <input type="text" list="dti-reface-codes" inputMode="text" autoCapitalize="characters" placeholder="DS, SD, DT..." value={normalizeDtiRefaceCode(rowData[field.key])} onChange={(event) => setRowData({ ...rowData, [field.key]: normalizeDtiRefaceCode(event.target.value) })} /> : <input type={field.kind === "number" ? "number" : "text"} step={field.kind === "number" ? "0.0001" : undefined} value={String(rowData[field.key] ?? "")} onChange={(event) => setRowData({ ...rowData, [field.key]: event.target.value })} />}</label>)}</div></fieldset>)}<div className={styles.editorActions}><button className={styles.primary} type="button" onClick={() => void saveItem()}>Save Row</button></div></div> : null}
      <div className={styles.itemList}>{items.map((item) => { const flagged = Object.values(item.row_data).filter((value) => value === true).length; return <article key={item.id} data-pending={Boolean(item.pendingMutationId)}><div><span>Row {item.sequence_number}</span><strong>Joint {displayValue(item.row_data.jointNumber)}</strong><small>{displayValue(item.row_data.serialNumber || item.row_data.description)}</small></div><div><span>UT / OD</span><strong>{displayValue(item.row_data.utThickness || item.row_data.boxOd)}</strong><small>{item.row_data.percentNominalWall ? `${(Number(item.row_data.percentNominalWall) * 100).toFixed(1)}% nominal wall` : "-"}</small></div><div><span>Findings</span><strong>{flagged}</strong><small>{item.pendingMutationId ? "Pending sync" : "Recorded"}</small></div><div className={styles.rowActions}><button type="button" onClick={() => editItem(item)}>Edit</button><button type="button" onClick={() => void deleteItem(item)}>Delete</button></div></article>; })}{!items.length ? <div className={styles.empty}>No {tab} inspection rows recorded.</div> : null}</div>
    </section></> : <section className={styles.inspectionSection}><div className={styles.sectionHead}><div><span>EMI</span><h2>Prove-Up Register</h2></div><button className={styles.primary} type="button" onClick={addProveUp}>Add Prove-Up</button></div>
      {proveUpOpen ? <div className={styles.proveUpForm}>{([['sequenceNumber','Row','number'],['jointNumber','Joint Number','text'],['serialNumber','Serial Number','text'],['flaw','Flaw','text'],['depthInches','Depth','number'],['adjacentWallInches','Adjacent Wall','number'],['remainingBodyWallInches','Remaining Body Wall','number'],['distanceFromEnd','Distance From End (B/P)','text'],['proveUpResult','Prove-Up Result','text']] as const).map(([key,label,type]) => <label key={key}><span>{label}</span><input type={type} step={type === "number" ? "0.0001" : undefined} value={proveUp[key]} onChange={(event) => setProveUp({ ...proveUp, [key]: event.target.value })} /></label>)}<button className={styles.primary} type="button" onClick={() => void saveProveUp()}>Save Prove-Up</button></div> : null}
      <div className={styles.itemList}>{proveUps.map((item) => <article key={item.id} data-pending={Boolean(item.pendingMutationId)}><div><span>Row {item.sequence_number}</span><strong>Joint {item.joint_number || "-"}</strong><small>{item.serial_number || "No serial"}</small></div><div><span>Flaw / Depth</span><strong>{item.flaw || "-"} / {item.depth_inches ?? "-"}</strong><small>Adjacent {item.adjacent_wall_inches ?? "-"}</small></div><div><span>Result</span><strong>{item.prove_up_result || "-"}</strong><small>{item.pendingMutationId ? "Pending sync" : item.distance_from_end || "-"}</small></div><div className={styles.rowActions}><button type="button" onClick={() => editProveUp(item)}>Edit</button><button type="button" onClick={() => void deleteProveUp(item)}>Delete</button></div></article>)}{!proveUps.length ? <div className={styles.empty}>No EMI prove-up rows recorded.</div> : null}</div>
    </section>}
    </div>
    {report ? <DtiInspectionPrintView report={report} items={allItems} proveUps={proveUps} /> : null}
  </main>;
}
