"use client";

import Image from "next/image";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { calculatePercentNominalWall, dtiInspectionCategoryOptions, dtiInspectionFieldsForPass, dtiRefaceOptions, normalizeDtiInspectionRowData, normalizeDtiRefaceCode, normalizeDtiYesNo, resolveDtiReportComponentType, summarizeDtiInspection, type DtiComponentType, type DtiInspectionPass } from "../../../../lib/dtiInspectionReport";
import { dtiClassifications, type DtiGradingResult } from "../../../../lib/dtiCriteriaEngine";
import { getValidAccessToken, redirectToLogin } from "../../../../lib/clientSession";
import { flushDtiMutationQueue, getDtiOfflineSnapshot, getQueuedDtiMutations, removeQueuedDtiMutation, saveDtiOfflineSnapshot, sendOrQueueDtiMutation, subscribeToDtiQueue, type DtiQueuedMutation } from "../../../../lib/dtiOfflineQueue";
import { goBackOrFallback } from "../../../../lib/navigation";
import DtiInspectionPrintView from "./DtiInspectionPrintView";
import styles from "../reports.module.css";

type Report = { id: string; report_number: string; operator_name: string; contractor_name: string | null; rig_number: string | null; report_date: string; field_invoice: string | null; inspection_crew: string | null; connection_size: string | null; connection_type: string | null; grade: string | null; state: string | null; inspection_scope: Record<string, unknown>; machine_shop: Record<string, unknown>; remarks: Record<string, unknown>; status: string; criteria_version_id?: string | null; criteria_snapshot?: Record<string, unknown> | null };
type Item = { id: string; report_id: string; component_type: DtiComponentType; sequence_number: number; row_data: Record<string, unknown>; grading_result?: DtiGradingResult | null; pendingMutationId?: string };
type ProveUp = { id: string; sequence_number: number; joint_number: string | null; serial_number: string | null; flaw: string | null; depth_inches: number | null; adjacent_wall_inches: number | null; remaining_body_wall_inches: number | null; distance_from_end: string | null; prove_up_result: string | null; pendingMutationId?: string };
type CriteriaVersion = { id: string; version_number: number; effective_date: string | null; nominal_wall_inches?: number | null; pipe_size?: string | null; weight_ppf?: number | null; grade?: string | null; connection?: string | null; criteria_set: { name: string; standard_type: string; component_type: DtiComponentType; customer_name: string | null } };
type ApiData = { ok?: boolean; report?: Report; items?: Item[]; proveUps?: ProveUp[]; criteriaVersions?: CriteriaVersion[]; error?: string; alertWarning?: string; gradingWarning?: string };
type Tab = DtiComponentType | "EMI Prove-Up";
const endpoint = "/api/dti/inspection-reports";
const blankProveUp = { proveUpId: "", sequenceNumber: "1", jointNumber: "", serialNumber: "", flaw: "", depthInches: "", adjacentWallInches: "", remainingBodyWallInches: "", distanceFromEnd: "", proveUpResult: "" };

function reportForm(report: Report, items: Item[] = []) {
  const componentType = resolveDtiReportComponentType(report.inspection_scope, items);
  const jointCount = Math.max(0, ...items.filter((item) => item.component_type === componentType).map((item) => item.sequence_number));
  return { operatorName: report.operator_name || "", contractorName: report.contractor_name || "", rigNumber: report.rig_number || "", reportDate: report.report_date || "", fieldInvoice: report.field_invoice || "", inspectionCrew: report.inspection_crew || "", connectionSize: report.connection_size || "", connectionType: report.connection_type || "", grade: report.grade || "", state: report.state || "", status: report.status || "Draft", jointCount: String(jointCount), criteriaVersionId: report.criteria_version_id || "", inspectionScope: report.inspection_scope || {}, machineShop: report.machine_shop || {}, remarks: report.remarks || {} };
}
function displayValue(value: unknown) { if (value === true) return "X"; if (value === false || value === null || value === undefined || value === "") return "-"; return String(value); }
function objectValue(source: Record<string, unknown>, key: string) { return String(source[key] ?? ""); }
function unique(values: Array<string | null | undefined>) { return [...new Set(values.filter((value): value is string => Boolean(value)))]; }
function pipeSizeNumber(value: string) {
  const [whole, fraction] = value.split("-");
  if (!fraction) return Number(whole) || 0;
  const [numerator, denominator] = fraction.split("/").map(Number);
  return (Number(whole) || 0) + (denominator ? numerator / denominator : 0);
}
function snapshottedCriteria(report: Report | undefined): CriteriaVersion | null {
  if (!report?.criteria_version_id || !report.criteria_snapshot) return null;
  const criteriaSet = report.criteria_snapshot.criteriaSet;
  const version = report.criteria_snapshot.version;
  if (!criteriaSet || typeof criteriaSet !== "object" || !version || typeof version !== "object") return null;
  const set = criteriaSet as Record<string, unknown>; const savedVersion = version as Record<string, unknown>; const spec = report.criteria_snapshot.tubularSpec as Record<string, unknown> | null | undefined;
  const nominalWall = Number(spec?.new_wall_inches);
  const nameParts = String(set.name ?? "").split("|").map((part) => part.trim());
  const managed = nameParts.length >= 5 && nameParts[0] === "DS-1 Premium";
  return { id: report.criteria_version_id, version_number: Number(savedVersion.version_number ?? 0), effective_date: String(savedVersion.effective_date ?? "") || null, nominal_wall_inches: Number.isFinite(nominalWall) && nominalWall > 0 ? nominalWall : null, pipe_size: managed ? nameParts[1] : null, weight_ppf: managed ? Number(nameParts[2]) : null, grade: managed ? nameParts[3] : null, connection: managed ? nameParts.slice(4).join(" | ") : null, criteria_set: { name: String(set.name ?? "Historical criteria"), standard_type: String(set.standard_type ?? ""), component_type: String(set.component_type ?? "Drill Pipe") as DtiComponentType, customer_name: String(set.customer_name ?? "") || null } };
}

export default function DtiInspectionReportEditor() {
  const params = useParams<{ reportId: string }>(); const reportId = String(params.reportId ?? ""); const snapshotKey = `inspection-report:${reportId}`;
  const [data, setData] = useState<ApiData | null>(null); const [tab, setTab] = useState<Tab>("Drill Pipe"); const [inspectionPass, setInspectionPass] = useState<DtiInspectionPass>("Box"); const [rowPage, setRowPage] = useState(0); const [rowSearch, setRowSearch] = useState(""); const [message, setMessage] = useState("Loading inspection report..."); const [online, setOnline] = useState(true); const [pending, setPending] = useState<DtiQueuedMutation[]>([]); const [syncing, setSyncing] = useState(false); const [exporting, setExporting] = useState(false); const [headerOpen, setHeaderOpen] = useState(false); const [header, setHeader] = useState<ReturnType<typeof reportForm> | null>(null); const [itemOpen, setItemOpen] = useState(false); const [itemId, setItemId] = useState(""); const [sequenceNumber, setSequenceNumber] = useState("1"); const [rowData, setRowData] = useState<Record<string, unknown>>({}); const [proveUpOpen, setProveUpOpen] = useState(false); const [proveUp, setProveUp] = useState(blankProveUp);
  const syncingRef = useRef(false);

  const loadPending = useCallback(async () => setPending((await getQueuedDtiMutations(reportId)).filter((item) => item.endpoint === endpoint)), [reportId]);
  const load = useCallback(async () => { try { const token = await getValidAccessToken(); if (!token) { const cached = await getDtiOfflineSnapshot<ApiData>(snapshotKey); if (cached && !navigator.onLine) { setData(cached.data); setTab(resolveDtiReportComponentType(cached.data.report?.inspection_scope, cached.data.items)); setHeader(cached.data.report ? reportForm(cached.data.report, cached.data.items) : null); setMessage("Offline report copy loaded."); return; } redirectToLogin(); return; } const request = await fetch(`${endpoint}?reportId=${encodeURIComponent(reportId)}`, { headers: { Authorization: `Bearer ${token}` } }); if (request.status === 401) { redirectToLogin(); return; } const body = await request.json() as ApiData; if (!request.ok) throw new Error(body.error || "TITAN could not load this report."); setData(body); setTab(resolveDtiReportComponentType(body.report?.inspection_scope, body.items)); if (body.report) setHeader(reportForm(body.report, body.items)); setMessage(""); await saveDtiOfflineSnapshot(snapshotKey, body).catch(() => undefined); } catch (error) { const cached = await getDtiOfflineSnapshot<ApiData>(snapshotKey).catch(() => null); if (cached) { setData(cached.data); setTab(resolveDtiReportComponentType(cached.data.report?.inspection_scope, cached.data.items)); if (cached.data.report) setHeader(reportForm(cached.data.report, cached.data.items)); setMessage(navigator.onLine ? "TITAN could not reach the server. Your saved report copy is available, and changes will sync when service returns." : "Offline report copy loaded. Changes will sync when service returns."); } else setMessage(error instanceof Error ? error.message : "TITAN could not load this report."); } }, [reportId, snapshotKey]);
  const sync = useCallback(async () => { if (syncingRef.current || !navigator.onLine) return; syncingRef.current = true; setSyncing(true); try { const result = await flushDtiMutationQueue(reportId); await loadPending(); if (result.synced) { setMessage(`${result.synced} saved change${result.synced === 1 ? "" : "s"} sent to TITAN.`); await load(); } else if (result.remaining && result.lastError) { setMessage(`TITAN could not send the saved change: ${result.lastError}`); } } finally { syncingRef.current = false; setSyncing(false); } }, [load, loadPending, reportId]);
  useEffect(() => { const timer = window.setTimeout(() => { setOnline(navigator.onLine); void load(); void loadPending().then(() => { if (navigator.onLine) void sync(); }); }, 0); const unsubscribe = subscribeToDtiQueue(() => void loadPending()); const onOnline = () => { setOnline(true); void sync(); }; const onOffline = () => setOnline(false); window.addEventListener("online", onOnline); window.addEventListener("offline", onOffline); return () => { window.clearTimeout(timer); unsubscribe(); window.removeEventListener("online", onOnline); window.removeEventListener("offline", onOffline); }; }, [load, loadPending, sync]);

  const serverItems = data?.items ?? []; const serverProveUps = data?.proveUps ?? []; const reportComponentType = resolveDtiReportComponentType(data?.report?.inspection_scope, serverItems);
  const currentCriteria = snapshottedCriteria(data?.report);
  const criteriaVersions = [...(currentCriteria && !(data?.criteriaVersions ?? []).some((version) => version.id === currentCriteria.id) ? [currentCriteria] : []), ...(data?.criteriaVersions ?? [])].filter((version) => version.criteria_set.component_type === reportComponentType);
  const selectedCriteria = criteriaVersions.find((version) => version.id === header?.criteriaVersionId) ?? (!header ? currentCriteria : null);
  const nominalWallThickness = reportComponentType === "Drill Pipe" && Number(selectedCriteria?.nominal_wall_inches) > 0 ? Number(selectedCriteria?.nominal_wall_inches) : null;
  const ds1Criteria = criteriaVersions.filter((version) => version.pipe_size && Number(version.weight_ppf) > 0 && version.grade && version.connection);
  const otherCriteria = criteriaVersions.filter((version) => !version.pipe_size || !version.weight_ppf || !version.grade || !version.connection);
  const criteriaScope = header?.inspectionScope ?? {};
  const hasCriteriaFilters = Object.prototype.hasOwnProperty.call(criteriaScope, "criteriaPipeSize");
  const criteriaPipeSize = hasCriteriaFilters ? objectValue(criteriaScope, "criteriaPipeSize") : selectedCriteria?.pipe_size || "";
  const criteriaWeight = hasCriteriaFilters ? objectValue(criteriaScope, "criteriaWeightPpf") : selectedCriteria?.weight_ppf ? String(selectedCriteria.weight_ppf) : "";
  const criteriaGrade = hasCriteriaFilters ? objectValue(criteriaScope, "criteriaGrade") : selectedCriteria?.grade || "";
  const criteriaConnection = hasCriteriaFilters ? objectValue(criteriaScope, "criteriaConnection") : selectedCriteria?.connection || "";
  const criteriaSizes = unique(ds1Criteria.map((version) => version.pipe_size)).sort((a, b) => pipeSizeNumber(a) - pipeSizeNumber(b));
  const criteriaWeights = unique(ds1Criteria.filter((version) => version.pipe_size === criteriaPipeSize).map((version) => String(version.weight_ppf))).sort((a, b) => Number(a) - Number(b));
  const criteriaGrades = unique(ds1Criteria.filter((version) => version.pipe_size === criteriaPipeSize && String(version.weight_ppf) === criteriaWeight).map((version) => version.grade)).sort();
  const criteriaConnections = unique(ds1Criteria.filter((version) => version.pipe_size === criteriaPipeSize && String(version.weight_ppf) === criteriaWeight && version.grade === criteriaGrade).map((version) => version.connection)).sort();
  const pendingItems = useMemo<Item[]>(() => pending.filter((entry) => entry.action === "save-item").map((entry) => ({ id: String(entry.payload.itemId || `pending-${entry.id}`), report_id: reportId, component_type: String(entry.payload.componentType) as DtiComponentType, sequence_number: Number(entry.payload.sequenceNumber), row_data: (entry.payload.rowData ?? {}) as Record<string, unknown>, grading_result: null, pendingMutationId: entry.id })), [pending, reportId]);
  const pendingItemIds = useMemo(() => new Set(pendingItems.filter((item) => !item.id.startsWith("pending-")).map((item) => item.id)), [pendingItems]);
  const deletedItemIds = useMemo(() => new Set(pending.filter((entry) => entry.action === "delete-item").map((entry) => String(entry.payload.itemId))), [pending]);
  const allItems = [...pendingItems, ...serverItems.filter((item) => !pendingItemIds.has(item.id) && !deletedItemIds.has(item.id))];
  const items = allItems.filter((item) => item.component_type === tab).sort((a, b) => a.sequence_number - b.sequence_number);
  const pendingProveUps = useMemo(() => pending.filter((entry) => entry.action === "save-prove-up").map((entry) => ({ id: String(entry.payload.proveUpId || `pending-${entry.id}`), sequence_number: Number(entry.payload.sequenceNumber), joint_number: String(entry.payload.jointNumber || ""), serial_number: String(entry.payload.serialNumber || ""), flaw: String(entry.payload.flaw || ""), depth_inches: Number(entry.payload.depthInches) || null, adjacent_wall_inches: Number(entry.payload.adjacentWallInches) || null, remaining_body_wall_inches: Number(entry.payload.remainingBodyWallInches) || null, distance_from_end: String(entry.payload.distanceFromEnd || ""), prove_up_result: String(entry.payload.proveUpResult || ""), pendingMutationId: entry.id })), [pending]);
  const pendingProveUpIds = useMemo(() => new Set(pendingProveUps.filter((item) => !item.id.startsWith("pending-")).map((item) => item.id)), [pendingProveUps]);
  const deletedProveUpIds = useMemo(() => new Set(pending.filter((entry) => entry.action === "delete-prove-up").map((entry) => String(entry.payload.proveUpId))), [pending]);
  const recordedProveUps = [...pendingProveUps, ...serverProveUps.filter((item) => !pendingProveUpIds.has(item.id) && !deletedProveUpIds.has(item.id))];
  const recordedProveUpIds = new Set(recordedProveUps.map((item) => item.id));
  const pendingLinkedProveUps = allItems.filter((item) => item.row_data.emiProveUp === true && !recordedProveUpIds.has(String(item.row_data.emiProveUpId ?? ""))).map((item, index) => ({ id: `linked-${item.id}`, sequence_number: Math.max(0, ...recordedProveUps.map((entry) => entry.sequence_number)) + index + 1, joint_number: String(item.row_data.jointNumber || item.sequence_number), serial_number: String(item.row_data.serialNumber || ""), flaw: "", depth_inches: null, adjacent_wall_inches: null, remaining_body_wall_inches: null, distance_from_end: "", prove_up_result: "", pendingMutationId: item.pendingMutationId }));
  const proveUps = [...recordedProveUps, ...pendingLinkedProveUps].sort((a, b) => a.sequence_number - b.sequence_number);

  async function saveAction(payload: Record<string, unknown>) { const result = await sendOrQueueDtiMutation<ApiData>({ ...payload, reportId }, endpoint); if (result.status === "saved") { const merged = { ...result.data, criteriaVersions: result.data.criteriaVersions ?? data?.criteriaVersions }; setData(merged); if (result.data.report) setHeader(reportForm(result.data.report, result.data.items)); await saveDtiOfflineSnapshot(snapshotKey, merged).catch(() => undefined); setMessage(result.data.gradingWarning || result.data.alertWarning || "Report saved."); } else { await loadPending(); setMessage(navigator.onLine ? "TITAN is retrying this saved change." : "Change saved on this device and queued for sync."); if (navigator.onLine && !(await getValidAccessToken())) redirectToLogin(); else if (navigator.onLine) window.setTimeout(() => void sync(), 1_000); } return result; }
  async function saveSetup() {
    if (!header) return;
    const jointCount = Number(header.jointCount);
    if (!Number.isInteger(jointCount) || jointCount < 0 || jointCount > 2000) { setMessage("Joint count must be a whole number from 0 to 2,000."); return; }
    const componentRows = allItems.filter((item) => item.component_type === reportComponentType);
    const rowsToRemove = componentRows.filter((item) => item.sequence_number > jointCount);
    if (rowsToRemove.length && !window.confirm(`Reducing the count to ${jointCount} will delete ${rowsToRemove.length} inspection row${rowsToRemove.length === 1 ? "" : "s"}. Continue?`)) return;
    const result = await saveAction({ action: "save-report", ...header, jointCount });
    if (result.status === "queued" && data) {
      const kept = (data.items ?? []).filter((item) => item.component_type !== reportComponentType || item.sequence_number <= jointCount);
      const existing = new Map(kept.filter((item) => item.component_type === reportComponentType).map((item) => [item.sequence_number, item]));
      const generated = Array.from({ length: jointCount }, (_, index) => index + 1).filter((number) => !existing.has(number)).map((number) => ({ id: `offline-count-${reportComponentType}-${number}`, report_id: reportId, component_type: reportComponentType, sequence_number: number, row_data: { jointNumber: String(number), ...(nominalWallThickness ? { nominalWallThickness } : {}) } }));
      const optimistic = { ...data, items: [...kept, ...generated] };
      setData(optimistic);
      await saveDtiOfflineSnapshot(snapshotKey, optimistic).catch(() => undefined);
    }
  }
  function selectCriteriaSize(value: string) {
    if (!header) return;
    setHeader({ ...header, criteriaVersionId: "", connectionSize: value, connectionType: "", grade: "", inspectionScope: { ...header.inspectionScope, criteriaPipeSize: value, criteriaWeightPpf: "", criteriaGrade: "", criteriaConnection: "" } });
  }
  function selectCriteriaWeight(value: string) {
    if (!header) return;
    setHeader({ ...header, criteriaVersionId: "", connectionType: "", grade: "", inspectionScope: { ...header.inspectionScope, criteriaPipeSize, criteriaWeightPpf: value, criteriaGrade: "", criteriaConnection: "" } });
  }
  function selectCriteriaGrade(value: string) {
    if (!header) return;
    setHeader({ ...header, criteriaVersionId: "", connectionType: "", grade: value, inspectionScope: { ...header.inspectionScope, criteriaPipeSize, criteriaWeightPpf: criteriaWeight, criteriaGrade: value, criteriaConnection: "" } });
  }
  function selectCriteriaConnection(value: string) {
    if (!header) return;
    const match = ds1Criteria.find((version) => version.pipe_size === criteriaPipeSize && String(version.weight_ppf) === criteriaWeight && version.grade === criteriaGrade && version.connection === value);
    setHeader({ ...header, criteriaVersionId: match?.id || "", connectionSize: criteriaPipeSize, connectionType: value, grade: criteriaGrade, inspectionScope: { ...header.inspectionScope, criteriaPipeSize, criteriaWeightPpf: criteriaWeight, criteriaGrade, criteriaConnection: value } });
  }
  function selectOtherCriteria(value: string) {
    if (!header) return;
    setHeader({ ...header, criteriaVersionId: value, inspectionScope: { ...header.inspectionScope, criteriaPipeSize: "", criteriaWeightPpf: "", criteriaGrade: "", criteriaConnection: "" } });
  }
  function addItem() { const next = Math.max(0, ...items.map((item) => item.sequence_number)) + 1; setInspectionPass("Full"); setItemId(""); setSequenceNumber(String(next)); setRowData({ jointNumber: String(next), ...(nominalWallThickness ? { nominalWallThickness } : {}) }); setItemOpen(true); }
  function editItem(item: Item, pass: DtiInspectionPass = inspectionPass) { setInspectionPass(pass); setItemId(item.id); setSequenceNumber(String(item.sequence_number)); setRowData(normalizeDtiInspectionRowData({ ...item.row_data, ...(nominalWallThickness ? { nominalWallThickness } : {}) })); setItemOpen(true); }
  async function saveItem(advance = false) {
    if (tab === "EMI Prove-Up") return;
    if (itemId.startsWith("pending-")) await removeQueuedDtiMutation(itemId.slice(8));
    const completion = inspectionPass === "Box" ? { boxPassComplete: true } : inspectionPass === "Pin" ? { pinPassComplete: true } : {};
    await saveAction({ action: "save-item", itemId: itemId.startsWith("pending-") ? "" : itemId, componentType: tab, sequenceNumber, rowData: normalizeDtiInspectionRowData({ ...rowData, ...completion, ...(nominalWallThickness ? { nominalWallThickness } : {}) }) });
    if (advance && inspectionPass !== "Full") {
      const completionKey = inspectionPass === "Box" ? "boxPassComplete" : "pinPassComplete";
      const next = items.find((item) => item.sequence_number > Number(sequenceNumber) && item.row_data[completionKey] !== true);
      if (next) { editItem(next, inspectionPass); return; }
      setMessage(`${inspectionPass} pass complete.`);
    }
    setItemOpen(false);
  }
  async function deleteItem(item: Item) { if (!window.confirm(`Delete ${item.component_type} row ${item.sequence_number}?`)) return; if (item.pendingMutationId) { await removeQueuedDtiMutation(item.pendingMutationId); setMessage("Pending row removed from this device."); } else await saveAction({ action: "delete-item", itemId: item.id }); }
  async function toggleEmiProveUp(item: Item, checked: boolean) {
    if (!checked && !window.confirm(`Remove Joint ${displayValue(item.row_data.jointNumber)} from the EMI Prove-Up sheet? Any prove-up details entered for this joint will also be deleted.`)) return;
    if (item.pendingMutationId) await removeQueuedDtiMutation(item.pendingMutationId);
    await saveAction({ action: "save-item", itemId: item.id.startsWith("pending-") ? "" : item.id, componentType: item.component_type, sequenceNumber: item.sequence_number, rowData: normalizeDtiInspectionRowData({ ...item.row_data, emiProveUp: checked, ...(nominalWallThickness ? { nominalWallThickness } : {}) }) });
  }
  function addProveUp() { const next = Math.max(0, ...proveUps.map((item) => item.sequence_number)) + 1; setProveUp({ ...blankProveUp, sequenceNumber: String(next) }); setProveUpOpen(true); }
  function editProveUp(item: ProveUp) { setProveUp({ proveUpId: item.id, sequenceNumber: String(item.sequence_number), jointNumber: item.joint_number || "", serialNumber: item.serial_number || "", flaw: item.flaw || "", depthInches: item.depth_inches === null ? "" : String(item.depth_inches), adjacentWallInches: item.adjacent_wall_inches === null ? "" : String(item.adjacent_wall_inches), remainingBodyWallInches: item.remaining_body_wall_inches === null ? "" : String(item.remaining_body_wall_inches), distanceFromEnd: item.distance_from_end || "", proveUpResult: item.prove_up_result || "" }); setProveUpOpen(true); }
  async function saveProveUp() { if (proveUp.proveUpId.startsWith("pending-")) await removeQueuedDtiMutation(proveUp.proveUpId.slice(8)); await saveAction({ action: "save-prove-up", ...proveUp, proveUpId: proveUp.proveUpId.startsWith("pending-") ? "" : proveUp.proveUpId }); setProveUpOpen(false); }
  async function deleteProveUp(item: ProveUp) { if (!window.confirm(`Delete EMI prove-up row ${item.sequence_number}?`)) return; if (item.pendingMutationId) { await removeQueuedDtiMutation(item.pendingMutationId); setMessage("Pending prove-up removed from this device."); } else await saveAction({ action: "delete-prove-up", proveUpId: item.id }); }
  async function exportOriginalWorkbook() {
    if (pending.length) { setMessage("Sync pending changes before exporting the original workbook."); return; }
    setExporting(true);
    try {
      const token = await getValidAccessToken();
      if (!token) { redirectToLogin(); return; }
      const request = await fetch(`${endpoint}/export?reportId=${encodeURIComponent(reportId)}`, { headers: { Authorization: `Bearer ${token}` } });
      if (request.status === 401) { redirectToLogin(); return; }
      if (!request.ok) { const body = await request.json().catch(() => ({})) as { error?: string }; throw new Error(body.error || "TITAN could not export the original workbook."); }
      const blob = await request.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a");
      anchor.href = url; anchor.download = `${report?.report_number || "DTI-Inspection-Report"}.xlsx`; document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url);
      setMessage("Original Excel report exported.");
    } catch (error) { setMessage(error instanceof Error ? error.message : "TITAN could not export the original workbook."); }
    finally { setExporting(false); }
  }
  const fields = tab === "EMI Prove-Up" ? [] : dtiInspectionFieldsForPass(tab, inspectionPass); const groups = [...new Set(fields.map((item) => item.group))]; const report = data?.report;
  const componentItems = tab === "EMI Prove-Up" ? [] : allItems.filter((item) => item.component_type === tab);
  const summary = summarizeDtiInspection(componentItems, reportComponentType);
  const scopePrefix = reportComponentType === "Drill Pipe" ? "drillPipe" : reportComponentType === "HWDP" ? "hwdp" : "subs";
  const reportTabs: Tab[] = [reportComponentType, "EMI Prove-Up"];
  const summaryEntries: Array<readonly [string, number]> = [['Inspected',summary.inspected],['Premium',summary.premium],['Rig Ready',summary.rigReady],['Machine Shop',summary.machineShop],['DBR',summary.dbr],['Box Refaces',summary.boxRefaces],['Pin Refaces',summary.pinRefaces],['Hardbands',summary.hardbands],['Damaged Hardbands',summary.damagedHardbands],['DBR Hardbands',summary.dbrHardbands]];
  if (reportComponentType === "HWDP") summaryEntries.push(['Center Pad 1',summary.centerPad1],['Center Pad 2',summary.centerPad2]);
  const automaticCounts = Object.fromEntries(dtiClassifications.map((classification) => [classification, componentItems.filter((item) => item.grading_result?.areas.Final.status === "Graded" && item.grading_result.areas.Final.classification === classification).length]));
  if (currentCriteria) for (const classification of dtiClassifications) summaryEntries.push([`Graded ${classification}`, automaticCounts[classification]]);
  const boxComplete = items.filter((item) => item.row_data.boxPassComplete === true).length;
  const pinComplete = items.filter((item) => item.row_data.pinPassComplete === true).length;
  const activePassComplete = inspectionPass === "Box" ? boxComplete : pinComplete;
  const nextPassItem = inspectionPass === "Full" ? null : items.find((item) => item.row_data[inspectionPass === "Box" ? "boxPassComplete" : "pinPassComplete"] !== true) ?? null;
  const normalizedRowSearch = rowSearch.trim().toLowerCase();
  const matchingItems = normalizedRowSearch ? items.filter((item) => [item.sequence_number, item.row_data.jointNumber, item.row_data.serialNumber, item.row_data.description].some((value) => String(value ?? "").toLowerCase().includes(normalizedRowSearch))) : items;
  const rowsPerPage = 50; const rowPageCount = Math.max(1, Math.ceil(matchingItems.length / rowsPerPage)); const safeRowPage = Math.min(rowPage, rowPageCount - 1);
  const visibleItems = normalizedRowSearch ? matchingItems.slice(0, rowsPerPage) : matchingItems.slice(safeRowPage * rowsPerPage, (safeRowPage + 1) * rowsPerPage);
  const livePercentNominalWall = calculatePercentNominalWall(rowData);

  return <main className={styles.page}>
    <div className={styles.screenOnly}>
    <header className={`${styles.header} titan-page-header`}><div className={styles.title}><Image src="/titan_logo.jpg" alt="TITAN" width={64} height={42} priority /><div><span>{report?.report_number || "DTI Inspection"}</span><h1>{reportComponentType} Inspection Report</h1></div></div><div className={styles.actions}><button type="button" onClick={() => goBackOrFallback("/dti/inspection-reports")}>Back</button><button type="button" onClick={() => void load()}>Refresh</button><button type="button" onClick={() => window.location.assign(`/dti/inspection-reports/${encodeURIComponent(reportId)}/print`)}>Print Preview</button><button type="button" onClick={() => void exportOriginalWorkbook()} disabled={exporting}>{exporting ? "Exporting" : "Export Excel"}</button><button type="button" onClick={() => { if (!headerOpen && report) setHeader(reportForm(report, allItems)); setHeaderOpen((value) => !value); }}>Report Setup</button></div></header>
    <section className={styles.syncBar} data-online={online}><div><span>{online ? "Online" : "Offline"}</span><strong>{pending.length ? `${pending.length} change${pending.length === 1 ? "" : "s"} waiting to sync` : "All changes synced"}</strong></div>{online && pending.length ? <button type="button" onClick={() => void sync()} disabled={syncing}>{syncing ? "Syncing" : "Sync Now"}</button> : null}</section>
    {message ? <div className={message.includes("saved") || message.includes("synced") ? styles.saved : styles.message}>{message}</div> : null}
    {report ? <section className={styles.reportBand}><div><span>Report Type</span><strong>{reportComponentType}</strong></div><div><span>Operator</span><strong>{report.operator_name}</strong></div><div><span>Contractor / Rig</span><strong>{report.contractor_name || "-"} / {report.rig_number || "-"}</strong></div><div><span>Connection</span><strong>{report.connection_size || "-"} / {report.connection_type || "-"}</strong></div><div><span>Acceptance Criteria</span><strong>{currentCriteria ? `${currentCriteria.criteria_set.name} / v${currentCriteria.version_number}` : "Not selected"}</strong></div><div><span>Status</span><strong>{report.status}</strong></div></section> : null}
    {headerOpen && header ? <section className={styles.editor}><div className={styles.sectionHead}><div><span>Report Header</span><h2>Job and Scope</h2></div><button type="button" onClick={() => setHeaderOpen(false)}>Close</button></div><div className={styles.formGrid}>{([['operatorName','Operator'],['contractorName','Contractor'],['rigNumber','Rig Number'],['reportDate','Date'],['fieldInvoice','Field Invoice'],['inspectionCrew','Inspection Crew'],['connectionSize','Connection Size'],['connectionType','Connection Type'],['grade','Grade'],['state','State']] as const).map(([key,label]) => <label key={key}><span>{label}</span><input type={key === "reportDate" ? "date" : "text"} value={String(header[key] ?? "")} onChange={(event) => setHeader({ ...header, [key]: event.target.value })} /></label>)}<label><span>Status</span><select value={header.status} onChange={(event) => setHeader({ ...header, status: event.target.value })}><option>Draft</option><option>In Progress</option><option>Complete</option></select></label></div>
      <div className={styles.setupSections}><fieldset><legend>{reportComponentType} Inspection</legend><div className={styles.scopeGrid}>
        <label><span>{reportComponentType === "Subs" ? "Tool Count" : "Joint Count"}</span><input type="number" min="0" max="2000" step="1" inputMode="numeric" value={header.jointCount} onChange={(event) => setHeader({ ...header, jointCount: event.target.value })} /></label>
        {reportComponentType === "Drill Pipe" && ds1Criteria.length ? <>
          <label><span>Pipe Size</span><select value={criteriaPipeSize} onChange={(event) => selectCriteriaSize(event.target.value)}><option value="">Select size</option>{criteriaSizes.map((value) => <option key={value} value={value}>{value} in</option>)}</select></label>
          <label><span>Weight</span><select value={criteriaWeight} disabled={!criteriaPipeSize} onChange={(event) => selectCriteriaWeight(event.target.value)}><option value="">Select weight</option>{criteriaWeights.map((value) => <option key={value} value={value}>{value} lb/ft</option>)}</select></label>
          <label><span>Grade</span><select value={criteriaGrade} disabled={!criteriaWeight} onChange={(event) => selectCriteriaGrade(event.target.value)}><option value="">Select grade</option>{criteriaGrades.map((value) => <option key={value} value={value}>{value}</option>)}</select></label>
          <label><span>Connection</span><select value={criteriaConnection} disabled={!criteriaGrade} onChange={(event) => selectCriteriaConnection(event.target.value)}><option value="">Select connection</option>{criteriaConnections.map((value) => <option key={value} value={value}>{value}</option>)}</select></label>
          {otherCriteria.length ? <label><span>Other Acceptance Criteria</span><select value={selectedCriteria && !selectedCriteria.pipe_size ? selectedCriteria.id : ""} onChange={(event) => selectOtherCriteria(event.target.value)}><option value="">Use DS-1 selections above</option>{otherCriteria.map((version) => <option key={version.id} value={version.id}>{version.criteria_set.name} / v{version.version_number}</option>)}</select></label> : null}
          <label><span>Nominal Wall Thickness</span><input type="number" readOnly aria-readonly="true" value={nominalWallThickness ?? ""} placeholder="Select connection" /></label>
        </> : <label><span>Acceptance Criteria</span><select value={header.criteriaVersionId} onChange={(event) => setHeader({ ...header, criteriaVersionId: event.target.value })}><option value="">Not selected</option>{criteriaVersions.map((version) => <option key={version.id} value={version.id}>{version.criteria_set.name} / v{version.version_number}{version.criteria_set.customer_name ? ` / ${version.criteria_set.customer_name}` : ""}</option>)}</select></label>}
        <label><span>Category</span><select value={objectValue(header.inspectionScope, `${scopePrefix}Category`)} onChange={(event) => setHeader({ ...header, inspectionScope: { ...header.inspectionScope, [`${scopePrefix}Category`]: event.target.value } })}><option value="">None</option>{dtiInspectionCategoryOptions.map((option) => <option key={option}>{option}</option>)}</select></label>
        <label><span>Additional 1</span><input value={objectValue(header.inspectionScope, `${scopePrefix}Additional1`)} onChange={(event) => setHeader({ ...header, inspectionScope: { ...header.inspectionScope, [`${scopePrefix}Additional1`]: event.target.value } })} /></label>
        <label><span>Additional 2</span><input value={objectValue(header.inspectionScope, `${scopePrefix}Additional2`)} onChange={(event) => setHeader({ ...header, inspectionScope: { ...header.inspectionScope, [`${scopePrefix}Additional2`]: event.target.value } })} /></label>
        <label><span>Remarks</span><textarea value={objectValue(header.remarks, scopePrefix)} onChange={(event) => setHeader({ ...header, remarks: { ...header.remarks, [scopePrefix]: event.target.value } })} /></label>
      </div></fieldset></div>
      <fieldset className={styles.setupFieldset}><legend>Machine Shop</legend><div className={styles.formGrid}>{([['name','Name'],['address','Address'],['contact','Contact'],['phone','Phone']] as const).map(([key,label]) => <label key={key}><span>{label}</span><input value={objectValue(header.machineShop, key)} onChange={(event) => setHeader({ ...header, machineShop: { ...header.machineShop, [key]: event.target.value } })} /></label>)}</div></fieldset>
      <div className={styles.editorActions}><button className={styles.primary} type="button" onClick={() => void saveSetup()}>Save Setup</button></div>
    </section> : null}
    <nav className={styles.tabs}>{reportTabs.map((value) => <button key={value} type="button" data-active={tab === value} onClick={() => { setTab(value); setRowPage(0); setRowSearch(""); setItemOpen(false); setProveUpOpen(false); }}>{value}<small>{value === "EMI Prove-Up" ? proveUps.length : allItems.filter((item) => item.component_type === value).length}</small></button>)}</nav>
    {tab !== "EMI Prove-Up" ? <><section className={styles.summaryPanel}><div className={styles.sectionHead}><div><span>{objectValue(report?.inspection_scope ?? {}, `${scopePrefix}Category`) || "Inspection Summary"}</span><h2>{reportComponentType} Totals</h2></div></div><div className={styles.summaryGrid}>{summaryEntries.map(([label,value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></section><section className={styles.inspectionSection}><div className={styles.sectionHead}><div><span>{reportComponentType}</span><h2>Rack Inspection</h2></div><button className={styles.primary} type="button" onClick={addItem}>Add Row</button></div>
      <div className={styles.passSelector}>{([['Box','Box Pass',boxComplete],['Pin','Pin Pass',pinComplete],['Full','Full Row',items.length]] as const).map(([pass,label,complete]) => <button key={pass} type="button" data-active={inspectionPass === pass} onClick={() => { setInspectionPass(pass); setItemOpen(false); }}><span>{label}</span><small>{pass === "Full" ? `${items.length} rows` : `${complete} / ${items.length} done`}</small></button>)}</div>
      {inspectionPass !== "Full" ? <div className={styles.passLaunch}><div><span>{inspectionPass} End</span><strong>{nextPassItem ? `Next unfinished: Row ${nextPassItem.sequence_number}` : `${inspectionPass} pass complete`}</strong></div><button className={styles.primary} type="button" disabled={!nextPassItem} onClick={() => nextPassItem && editItem(nextPassItem, inspectionPass)}>{activePassComplete === 0 ? `Start ${inspectionPass} Pass` : `Continue ${inspectionPass} Pass`}</button></div> : null}
      {itemOpen ? <div className={styles.rowEditor}><div className={styles.rowEditorHead}><strong>Row {sequenceNumber} / {inspectionPass === "Full" ? "Full Joint" : `${inspectionPass} End`}</strong><button type="button" onClick={() => setItemOpen(false)}>Close</button></div><datalist id="dti-reface-codes">{dtiRefaceOptions.map((option) => <option key={option.value} value={option.value} />)}</datalist>{groups.map((group) => <fieldset key={group}><legend>{group}</legend><div className={styles.fieldGrid}>{fields.filter((item) => item.group === group).map((field) => <label key={field.key} data-kind={field.kind}><span>{field.label}{inspectionPass === "Full" && field.end ? ` / ${field.end}` : ""}</span>{field.kind === "flag" ? <input type="checkbox" checked={rowData[field.key] === true} onChange={(event) => setRowData({ ...rowData, [field.key]: event.target.checked })} /> : field.kind === "yesno" ? <select value={normalizeDtiYesNo(rowData[field.key])} onChange={(event) => setRowData({ ...rowData, [field.key]: event.target.value })}><option value="">Select</option><option value="Yes">Yes</option><option value="No">No</option></select> : field.kind === "calculated" ? <input type="text" readOnly aria-readonly="true" value={livePercentNominalWall === null ? "" : `${(livePercentNominalWall * 100).toFixed(1)}%`} /> : field.key === "nominalWallThickness" && nominalWallThickness ? <input type="number" readOnly aria-readonly="true" value={nominalWallThickness} /> : field.kind === "reface" ? <input type="text" list="dti-reface-codes" inputMode="text" autoCapitalize="characters" placeholder="DS, SD, DT..." value={normalizeDtiRefaceCode(rowData[field.key])} onChange={(event) => setRowData({ ...rowData, [field.key]: normalizeDtiRefaceCode(event.target.value) })} /> : <input type={field.kind === "number" ? "number" : "text"} step={field.kind === "number" ? "0.0001" : undefined} value={String(rowData[field.key] ?? "")} onChange={(event) => setRowData({ ...rowData, [field.key]: event.target.value })} />}</label>)}</div></fieldset>)}<div className={styles.editorActions}><button type="button" onClick={() => void saveItem(false)}>{inspectionPass === "Full" ? "Save Row" : "Save"}</button>{inspectionPass !== "Full" ? <button className={styles.primary} type="button" onClick={() => void saveItem(true)}>Save &amp; Next</button> : null}</div></div> : null}
      <div className={styles.rowFinder}><label><span>Find Row</span><input type="search" inputMode="search" placeholder="Row, joint, serial, or description" value={rowSearch} onChange={(event) => { setRowSearch(event.target.value); setRowPage(0); }} /></label>{!normalizedRowSearch && rowPageCount > 1 ? <div><button type="button" disabled={safeRowPage === 0} onClick={() => setRowPage((page) => Math.max(0, page - 1))}>Previous</button><strong>Rows {safeRowPage * rowsPerPage + 1}-{Math.min((safeRowPage + 1) * rowsPerPage, items.length)} of {items.length}</strong><button type="button" disabled={safeRowPage >= rowPageCount - 1} onClick={() => setRowPage((page) => Math.min(rowPageCount - 1, page + 1))}>Next</button></div> : <strong>{normalizedRowSearch ? `${matchingItems.length} match${matchingItems.length === 1 ? "" : "es"}` : `${items.length} rows`}</strong>}</div>
      <div className={styles.itemList}>{visibleItems.map((item) => { const flagged = Object.entries(item.row_data).filter(([key,value]) => !key.endsWith("PassComplete") && key !== "emiProveUp" && value === true).length; const boxDone = item.row_data.boxPassComplete === true; const pinDone = item.row_data.pinPassComplete === true; const hasProveUp = item.row_data.emiProveUp === true; const finalGrade = item.grading_result?.areas.Final; const gradeReason = finalGrade?.reasons[0]?.reason; const gradeLabel = finalGrade?.classification ? `${finalGrade.classification}${finalGrade.status === "Pending" ? " / Pending" : ""}` : finalGrade?.status || (currentCriteria ? "Not graded" : "No criteria"); return <article key={item.id} data-pending={Boolean(item.pendingMutationId)}><div><span>Row {item.sequence_number}</span><strong>Joint {displayValue(item.row_data.jointNumber)}</strong><small>{displayValue(item.row_data.serialNumber || item.row_data.description)}</small></div><div><span>Rack Progress</span><strong>{boxDone ? "Box done" : "Box pending"}</strong><small>{pinDone ? "Pin done" : "Pin pending"}</small><label className={styles.proveUpCheck} data-checked={hasProveUp}><input type="checkbox" checked={hasProveUp} onChange={(event) => void toggleEmiProveUp(item, event.target.checked)} /><span>EMI Prove-Up</span></label></div><div><span>Findings</span><strong>{flagged}</strong><small>{item.pendingMutationId ? "Pending sync" : "Recorded"}</small></div><div className={styles.classification} data-classification={finalGrade?.classification || finalGrade?.status || "Not Evaluated"}><span>Classification</span><strong>{gradeLabel}</strong><small>{gradeReason || (finalGrade?.status === "Pending" ? `${finalGrade.pendingRules} value${finalGrade.pendingRules === 1 ? "" : "s"} needed` : finalGrade?.status || "Select criteria in Report Setup")}</small></div><div className={styles.passActions}><button type="button" data-done={boxDone} onClick={() => editItem(item, "Box")}>Box</button><button type="button" data-done={pinDone} onClick={() => editItem(item, "Pin")}>Pin</button><button type="button" onClick={() => editItem(item, "Full")}>Full</button><button type="button" onClick={() => void deleteItem(item)}>Delete</button></div></article>; })}{!matchingItems.length ? <div className={styles.empty}>{normalizedRowSearch ? "No inspection rows match that search." : `No ${tab} inspection rows recorded.`}</div> : null}</div>
    </section></> : <section className={styles.inspectionSection}><div className={styles.sectionHead}><div><span>EMI</span><h2>Prove-Up Register</h2></div><button className={styles.primary} type="button" onClick={addProveUp}>Add Prove-Up</button></div>
      {proveUpOpen ? <div className={styles.proveUpForm}>{([['sequenceNumber','Row','number'],['jointNumber','Joint Number','text'],['serialNumber','Serial Number','text'],['flaw','Flaw','text'],['depthInches','Depth','number'],['adjacentWallInches','Adjacent Wall','number'],['remainingBodyWallInches','Remaining Body Wall','number'],['distanceFromEnd','Distance From End (B/P)','text'],['proveUpResult','Prove-Up Result','text']] as const).map(([key,label,type]) => <label key={key}><span>{label}</span><input type={type} step={type === "number" ? "0.0001" : undefined} value={proveUp[key]} onChange={(event) => setProveUp({ ...proveUp, [key]: event.target.value })} /></label>)}<button className={styles.primary} type="button" onClick={() => void saveProveUp()}>Save Prove-Up</button></div> : null}
      <div className={styles.itemList}>{proveUps.map((item) => <article key={item.id} data-pending={Boolean(item.pendingMutationId)}><div><span>Row {item.sequence_number}</span><strong>Joint {item.joint_number || "-"}</strong><small>{item.serial_number || "No serial"}</small></div><div><span>Flaw / Depth</span><strong>{item.flaw || "-"} / {item.depth_inches ?? "-"}</strong><small>Adjacent {item.adjacent_wall_inches ?? "-"}</small></div><div><span>Result</span><strong>{item.prove_up_result || "-"}</strong><small>{item.pendingMutationId ? "Pending sync" : item.distance_from_end || "-"}</small></div><div className={styles.rowActions}><button type="button" onClick={() => editProveUp(item)}>Edit</button><button type="button" onClick={() => void deleteProveUp(item)}>Delete</button></div></article>)}{!proveUps.length ? <div className={styles.empty}>No EMI prove-up rows recorded.</div> : null}</div>
    </section>}
    </div>
    {report ? <DtiInspectionPrintView report={report} items={allItems} proveUps={proveUps} /> : null}
  </main>;
}
