"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import DtiProcedureMenu from "../../components/DtiProcedureMenu";
import { goBackOrFallback } from "../../../lib/navigation";
import { supabase } from "../../../lib/supabase";
import styles from "./deviations.module.css";

type Job = { id: string; job_number: string; title: string; lifecycle_status: string; customer_name: string | null; rig_name: string | null; location_name: string | null };
type Document = { id: string; job_id: string; document_type: string; display_name: string; created_at: string };
type Deviation = { id: string; deviation_number: string; job_id: string; component: string | null; joint_ids: string | null; quantity: number | null; defect_type: string; location_on_component: string | null; measurements: string | null; controlling_criteria: string | null; justification: string | null; operational_risk: string | null; inspector_recommendation: string | null; communication_method: string | null; written_confirmation: boolean; confirmation_document_id: string | null; status: "Draft" | "Submitted" | "Approved" | "Voided"; void_reason: string | null; third_party_monitor_present: boolean; third_party_monitor_name: string | null; third_party_monitor_company: string | null; risk_level: string | null; economic_impact: string | null; trend_across_string: string | null; customer_rep_name: string | null; customer_rep_title: string | null; customer_company: string | null; customer_authorized_on: string | null; pathfinder_inspector_name: string | null; pathfinder_inspector_signed_on: string | null; lead_inspector_name: string | null; lead_inspector_signed_on: string | null; customer_signature_name: string | null; customer_signed_on: string | null; confirmation_attached: boolean; attached_to_job_report: boolean; affected_joints_marked: boolean; manager_copy_filed: boolean; approved_at: string | null; updated_at: string };
type ResponseData = { ok?: boolean; jobs?: Job[]; deviations?: Deviation[]; documents?: Document[]; metrics?: { total: number; draft: number; submitted: number; approved: number }; error?: string };
type Form = { component: string; jointIds: string; quantity: string; defectType: string; locationOnComponent: string; measurements: string; controllingCriteria: string; justification: string; inspectorRecommendation: string; communicationMethod: string; confirmationDocumentId: string; thirdPartyMonitorPresent: boolean; thirdPartyMonitorName: string; thirdPartyMonitorCompany: string; riskLevel: string; economicImpact: string; trendAcrossString: string; customerRepName: string; customerRepTitle: string; customerCompany: string; customerAuthorizedOn: string; pathfinderInspectorName: string; pathfinderInspectorSignedOn: string; leadInspectorName: string; leadInspectorSignedOn: string; customerSignatureName: string; customerSignedOn: string; confirmationAttached: boolean; attachedToJobReport: boolean; affectedJointsMarked: boolean; managerCopyFiled: boolean };

function value(value: string | null | undefined) { return value || ""; }
function toForm(item: Deviation): Form { return { component: value(item.component), jointIds: value(item.joint_ids), quantity: String(item.quantity ?? 1), defectType: item.defect_type, locationOnComponent: value(item.location_on_component), measurements: value(item.measurements), controllingCriteria: value(item.controlling_criteria), justification: value(item.justification), inspectorRecommendation: value(item.inspector_recommendation) || "Accept with Deviation", communicationMethod: value(item.communication_method), confirmationDocumentId: value(item.confirmation_document_id), thirdPartyMonitorPresent: Boolean(item.third_party_monitor_present), thirdPartyMonitorName: value(item.third_party_monitor_name), thirdPartyMonitorCompany: value(item.third_party_monitor_company), riskLevel: ["Low", "Moderate", "High"].includes(value(item.risk_level || item.operational_risk)) ? value(item.risk_level || item.operational_risk) : "", economicImpact: value(item.economic_impact), trendAcrossString: value(item.trend_across_string), customerRepName: value(item.customer_rep_name), customerRepTitle: value(item.customer_rep_title), customerCompany: value(item.customer_company), customerAuthorizedOn: value(item.customer_authorized_on), pathfinderInspectorName: value(item.pathfinder_inspector_name), pathfinderInspectorSignedOn: value(item.pathfinder_inspector_signed_on), leadInspectorName: value(item.lead_inspector_name), leadInspectorSignedOn: value(item.lead_inspector_signed_on), customerSignatureName: value(item.customer_signature_name), customerSignedOn: value(item.customer_signed_on), confirmationAttached: Boolean(item.confirmation_attached), attachedToJobReport: Boolean(item.attached_to_job_report), affectedJointsMarked: Boolean(item.affected_joints_marked), managerCopyFiled: Boolean(item.manager_copy_filed) }; }
function date(value: string | null) { if (!value) return "-"; const parsed = new Date(`${value}${value.length === 10 ? "T12:00:00" : ""}`); return Number.isNaN(parsed.getTime()) ? value : parsed.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }); }
function normalized(value: unknown) { return String(value ?? "").trim().toLowerCase(); }

export default function DtiDeviationRegisterPage() {
  const [data, setData] = useState<ResponseData | null>(null); const [message, setMessage] = useState("Loading OMS-202 deviation register..."); const [search, setSearch] = useState(""); const [status, setStatus] = useState("Open"); const [customer, setCustomer] = useState("All Customers"); const [selected, setSelected] = useState<Deviation | null>(null); const [form, setForm] = useState<Form | null>(null); const [saving, setSaving] = useState(false); const [voidReason, setVoidReason] = useState(""); const [opening, setOpening] = useState("");
  const load = useCallback(async () => { setMessage("Loading OMS-202 deviation register..."); try { const { data: auth } = await supabase.auth.getSession(); const token = auth.session?.access_token; if (!token) return window.location.assign("/login"); const response = await fetch("/api/dti/deviations", { headers: { Authorization: `Bearer ${token}` } }); const body = await response.json() as ResponseData; if (!response.ok) throw new Error(body.error || "TITAN could not load deviations."); setData(body); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "TITAN could not load deviations."); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const jobs = useMemo(() => new Map((data?.jobs ?? []).map((job) => [job.id, job])), [data?.jobs]);
  const customers = useMemo(() => [...new Set((data?.jobs ?? []).map((job) => job.customer_name).filter((item): item is string => Boolean(item)))].sort(), [data?.jobs]);
  const visible = useMemo(() => (data?.deviations ?? []).filter((item) => { const job = jobs.get(item.job_id); if (status === "Open" && ["Approved", "Voided"].includes(item.status)) return false; if (status !== "Open" && status !== "All" && item.status !== status) return false; if (customer !== "All Customers" && job?.customer_name !== customer) return false; const query = normalized(search); return !query || [item.deviation_number, item.defect_type, item.component, item.joint_ids, item.customer_rep_name, item.customer_company, job?.job_number, job?.title, job?.customer_name, job?.rig_name].some((entry) => normalized(entry).includes(query)); }), [data?.deviations, jobs, search, status, customer]);
  function edit(item: Deviation) { setSelected(item); setForm(toForm(item)); setVoidReason(""); setMessage(""); document.getElementById("deviation-editor")?.scrollIntoView({ behavior: "smooth", block: "start" }); }
  async function action(name: "save" | "submit" | "approve" | "void") {
    if (!selected || saving) return;
    setSaving(true); setMessage("");
    try {
      const { data: auth } = await supabase.auth.getSession(); const token = auth.session?.access_token;
      if (!token) return window.location.assign("/login");
      const request = async (requestedAction: string) => {
        const response = await fetch("/api/dti/deviations", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ action: requestedAction, deviationId: selected.id, ...(form ?? {}), voidReason }) });
        const body = await response.json() as ResponseData;
        if (!response.ok) throw new Error(body.error || "TITAN could not update this deviation.");
        return body;
      };
      if (name === "submit") await request("save");
      const body = await request(name);
      setData(body); setSelected(null); setForm(null); setVoidReason("");
      setMessage(`${selected.deviation_number} ${name === "save" ? "saved" : name === "submit" ? "submitted" : name === "approve" ? "approved" : "voided"}.`);
    } catch (error) { setMessage(error instanceof Error ? error.message : "TITAN could not update this deviation."); }
    finally { setSaving(false); }
  }
  async function openEvidence(documentId: string) { const tab = window.open("about:blank", "_blank"); setOpening(documentId); try { const { data: auth } = await supabase.auth.getSession(); const token = auth.session?.access_token; if (!token) throw new Error("Your TITAN session expired."); const response = await fetch(`/api/crm/job-lifecycle?documentId=${encodeURIComponent(documentId)}`, { headers: { Authorization: `Bearer ${token}` } }); const body = await response.json() as { url?: string; error?: string }; if (!response.ok || !body.url) throw new Error(body.error || "TITAN could not open the evidence."); if (tab) tab.location.replace(body.url); else window.location.assign(body.url); } catch (error) { tab?.close(); setMessage(error instanceof Error ? error.message : "TITAN could not open the evidence."); } finally { setOpening(""); } }
  const update = (changes: Partial<Form>) => setForm((current) => current ? { ...current, ...changes } : current);
  const jobDocuments = form && selected ? (data?.documents ?? []).filter((item) => item.job_id === selected.job_id) : [];

  return <main className={styles.page}>
    <header className={`${styles.header} titan-page-header`}><div className={styles.title}><Image src="/titan_logo.jpg" alt="TITAN" width={64} height={42} priority /><div><span>DTI / OMS-202</span><h1>Deviation Register</h1></div></div><div className={styles.actions}><button type="button" onClick={() => goBackOrFallback("/dti")}>Back</button><Link href="/dti">DTI Management</Link><DtiProcedureMenu procedures={[{ documentNumber: "OMS-202", label: "Deviation Agreement" }, { documentNumber: "OMS-109", label: "Escalation Flow" }, { documentNumber: "OMS-105", label: "Defect Decisions" }]} /><button type="button" onClick={() => void load()}>Refresh</button></div></header>
    {data?.metrics ? <section className={styles.metrics}><article><span>Total Records</span><strong>{data.metrics.total}</strong></article><article><span>Draft</span><strong>{data.metrics.draft}</strong></article><article data-alert={data.metrics.submitted > 0}><span>Awaiting Approval</span><strong>{data.metrics.submitted}</strong></article><article><span>Approved</span><strong>{data.metrics.approved}</strong></article></section> : null}
    <section className={styles.filters}><label className={styles.search}><span>Search</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Deviation, job, customer, rig, component, joint..." /></label><label><span>Status</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option>Open</option><option>Draft</option><option>Submitted</option><option>Approved</option><option>Voided</option><option>All</option></select></label><label><span>Customer</span><select value={customer} onChange={(event) => setCustomer(event.target.value)}><option>All Customers</option>{customers.map((item) => <option key={item}>{item}</option>)}</select></label></section>
    {message ? <div className={message.includes("saved") || message.includes("submitted") || message.includes("approved") || message.includes("voided") ? styles.success : styles.message}>{message}</div> : null}
    <div className={styles.resultCount}>{visible.length} deviation{visible.length === 1 ? "" : "s"}</div>
    <section className={styles.list}>{visible.map((item) => { const job = jobs.get(item.job_id); return <article key={item.id} data-status={item.status}><div className={styles.recordHead}><div><span>{item.deviation_number} / {job?.job_number || "DTI Job"}</span><strong>{item.defect_type}</strong><small>{job?.customer_name || "No customer"} / {job?.rig_name || job?.title || "No rig"}</small></div><b>{item.status}</b></div><dl><div><dt>Component / Joints</dt><dd>{item.component || "-"} / {item.joint_ids || "-"}</dd></div><div><dt>Quantity</dt><dd>{item.quantity ?? "-"}</dd></div><div><dt>Risk</dt><dd>{item.risk_level || item.operational_risk || "Not assessed"}</dd></div><div><dt>Written Evidence</dt><dd>{item.confirmation_document_id ? "Attached" : "Missing"}</dd></div><div><dt>Customer Rep</dt><dd>{item.customer_rep_name || "Not recorded"}</dd></div><div><dt>Updated</dt><dd>{date(item.updated_at)}</dd></div></dl>{item.void_reason ? <p><strong>Void reason:</strong> {item.void_reason}</p> : null}<div className={styles.recordActions}><Link href={`/dti/job-execution/${encodeURIComponent(item.job_id)}`}>Execution</Link><Link href={`/crm/jobs/${encodeURIComponent(item.job_id)}`}>Job Documents</Link>{item.confirmation_document_id ? <button type="button" onClick={() => void openEvidence(item.confirmation_document_id!)} disabled={opening === item.confirmation_document_id}>{opening === item.confirmation_document_id ? "Opening..." : "Open Evidence"}</button> : null}{item.status !== "Voided" ? <button className={styles.primary} type="button" onClick={() => edit(item)}>{item.status === "Draft" ? "Review / Edit" : item.status === "Submitted" ? "Review Approval" : "View Record"}</button> : null}</div></article>; })}</section>
    {!visible.length && !message ? <div className={styles.empty}>No DTI deviations match these filters.</div> : null}

    {selected && form ? <section id="deviation-editor" className={styles.editor}><div className={styles.editorHead}><div><span>{selected.deviation_number} / OMS-202</span><h2>{selected.status === "Draft" ? "Complete Deviation Agreement" : selected.status === "Submitted" ? "Approval Review" : "Approved Deviation"}</h2></div><button type="button" onClick={() => { setSelected(null); setForm(null); }}>Close</button></div>
      <fieldset disabled={selected.status !== "Draft" || saving}><legend>Job and Component</legend><div className={styles.formGrid}><label><span>Component</span><input value={form.component} onChange={(e) => update({ component: e.target.value })} /></label><label><span>Joint / Component IDs</span><input value={form.jointIds} onChange={(e) => update({ jointIds: e.target.value })} /></label><label><span>Quantity</span><input type="number" min="1" value={form.quantity} onChange={(e) => update({ quantity: e.target.value })} /></label><label><span>Location on Component</span><select value={form.locationOnComponent} onChange={(e) => update({ locationOnComponent: e.target.value })}><option value="">Select</option><option>Tube Body</option><option>Slip Area</option><option>Upset / Transition</option><option>Tool Joint / Threads</option><option>Seal / Shoulder</option><option>BHA High-Load</option><option>Other</option></select></label><label className={styles.wide}><span>Condition / Defect Type</span><input value={form.defectType} onChange={(e) => update({ defectType: e.target.value })} /></label><label className={styles.wide}><span>Measurements / RBW</span><textarea value={form.measurements} onChange={(e) => update({ measurements: e.target.value })} /></label><label className={styles.check}><input type="checkbox" checked={form.thirdPartyMonitorPresent} onChange={(e) => update({ thirdPartyMonitorPresent: e.target.checked })} /><span>Third-party monitor on location</span></label>{form.thirdPartyMonitorPresent ? <><label><span>Monitor Name</span><input value={form.thirdPartyMonitorName} onChange={(e) => update({ thirdPartyMonitorName: e.target.value })} /></label><label><span>Monitor Company</span><input value={form.thirdPartyMonitorCompany} onChange={(e) => update({ thirdPartyMonitorCompany: e.target.value })} /></label></> : null}</div></fieldset>
      <fieldset disabled={selected.status !== "Draft" || saving}><legend>Basis and Risk</legend><div className={styles.formGrid}><label className={styles.wide}><span>Criteria Requested / Accepted</span><textarea value={form.controllingCriteria} onChange={(e) => update({ controllingCriteria: e.target.value })} /></label><label className={styles.wide}><span>Technical Justification</span><textarea value={form.justification} onChange={(e) => update({ justification: e.target.value })} /></label><label><span>Operational Risk</span><select value={form.riskLevel} onChange={(e) => update({ riskLevel: e.target.value })}><option value="">Select</option><option>Low</option><option>Moderate</option><option>High</option></select></label><label><span>Economic Impact</span><select value={form.economicImpact} onChange={(e) => update({ economicImpact: e.target.value })}><option value="">Select</option><option>Low</option><option>Moderate</option><option>High</option></select></label><label><span>Trend Across String</span><select value={form.trendAcrossString} onChange={(e) => update({ trendAcrossString: e.target.value })}><option value="">Select</option><option>Isolated</option><option>Several Joints</option><option>Widespread</option></select></label><label><span>Inspector Recommendation</span><select value={form.inspectorRecommendation} onChange={(e) => update({ inspectorRecommendation: e.target.value })}><option>Reject per Standard</option><option>Accept with Deviation</option><option>Further Evaluation / Re-Test</option></select></label></div></fieldset>
      <fieldset disabled={selected.status !== "Draft" || saving}><legend>Customer Authorization and Signatures</legend><div className={styles.formGrid}><label><span>Customer Representative</span><input value={form.customerRepName} onChange={(e) => update({ customerRepName: e.target.value })} /></label><label><span>Title</span><input value={form.customerRepTitle} onChange={(e) => update({ customerRepTitle: e.target.value })} /></label><label><span>Company</span><input value={form.customerCompany} onChange={(e) => update({ customerCompany: e.target.value })} /></label><label><span>Authorization Date</span><input type="date" value={form.customerAuthorizedOn} onChange={(e) => update({ customerAuthorizedOn: e.target.value })} /></label><label><span>Communication Method</span><select value={form.communicationMethod} onChange={(e) => update({ communicationMethod: e.target.value })}><option value="">Select</option><option>Email</option><option>Written Approval</option><option>Customer Portal</option><option>Other Written</option></select></label><label className={styles.wide}><span>Written Confirmation Evidence</span><select value={form.confirmationDocumentId} onChange={(e) => update({ confirmationDocumentId: e.target.value, confirmationAttached: Boolean(e.target.value) })}><option value="">Select attached job document</option>{jobDocuments.map((document) => <option key={document.id} value={document.id}>{document.document_type} / {document.display_name}</option>)}</select></label><label><span>Pathfinder Inspector</span><input value={form.pathfinderInspectorName} onChange={(e) => update({ pathfinderInspectorName: e.target.value })} /></label><label><span>Date</span><input type="date" value={form.pathfinderInspectorSignedOn} onChange={(e) => update({ pathfinderInspectorSignedOn: e.target.value })} /></label><label><span>Lead Inspector</span><input value={form.leadInspectorName} onChange={(e) => update({ leadInspectorName: e.target.value })} /></label><label><span>Date</span><input type="date" value={form.leadInspectorSignedOn} onChange={(e) => update({ leadInspectorSignedOn: e.target.value })} /></label><label><span>Customer Signature Name</span><input value={form.customerSignatureName} onChange={(e) => update({ customerSignatureName: e.target.value })} /></label><label><span>Date</span><input type="date" value={form.customerSignedOn} onChange={(e) => update({ customerSignedOn: e.target.value })} /></label></div></fieldset>
      <fieldset disabled={selected.status !== "Draft" || saving}><legend>Filing and Distribution</legend><div className={styles.checkGrid}><label><input type="checkbox" checked={form.confirmationAttached} onChange={(e) => update({ confirmationAttached: e.target.checked })} /><span>Written confirmation attached</span></label><label><input type="checkbox" checked={form.attachedToJobReport} onChange={(e) => update({ attachedToJobReport: e.target.checked })} /><span>Form attached to job report</span></label><label><input type="checkbox" checked={form.affectedJointsMarked} onChange={(e) => update({ affectedJointsMarked: e.target.checked })} /><span>Affected joints marked / stenciled</span></label><label><input type="checkbox" checked={form.managerCopyFiled} onChange={(e) => update({ managerCopyFiled: e.target.checked })} /><span>Service Line Manager copy filed</span></label></div></fieldset>
      {selected.status === "Approved" ? <div className={styles.approved}>Approved {date(selected.approved_at)} with written customer authorization.</div> : null}
      <div className={styles.editorActions}>{selected.status === "Draft" ? <><button type="button" onClick={() => void action("save")} disabled={saving}>Save Draft</button><button className={styles.primary} type="button" onClick={() => void action("submit")} disabled={saving}>Submit for Approval</button></> : null}{selected.status === "Submitted" ? <button className={styles.primary} type="button" onClick={() => void action("approve")} disabled={saving}>Approve Deviation</button> : null}{selected.status !== "Voided" ? <><input value={voidReason} onChange={(e) => setVoidReason(e.target.value)} placeholder="Void reason" /><button className={styles.danger} type="button" onClick={() => void action("void")} disabled={saving || !voidReason.trim()}>Void</button></> : null}</div>
    </section> : null}
  </main>;
}
