"use client";

import { useCallback, useEffect, useState } from "react";
import { supabase } from "../../../../lib/supabase";
import styles from "./preJob.module.css";

type Scope = { component_family: string; component_description: string; service_category: string; connection_type: string; estimated_quantity: number | null; baseline_scope: string[]; additional_requirements: string | null; customer_spec_document_id: string | null; customer_confirmed: boolean; customer_confirmed_by: string | null; customer_confirmed_on: string | null; status: "Draft" | "Confirmed" };
type Document = { id: string; display_name: string; document_type: string };
type Response = { scope?: Scope | null; documents?: Document[]; error?: string };
type Props = { jobId: string; onStatusChange: (ready: boolean, configured: boolean) => void };
const today = new Date().toISOString().slice(0, 10);
const blank = { componentFamily: "Drill Pipe", componentDescription: "", serviceCategory: "", connectionType: "API", estimatedQuantity: "", additionalRequirements: "", customerSpecDocumentId: "", customerConfirmed: false, customerConfirmedBy: "", customerConfirmedOn: today };

export default function DtiJobScopePanel({ jobId, onStatusChange }: Props) {
  const [form, setForm] = useState(blank); const [scope, setScope] = useState<Scope | null>(null); const [documents, setDocuments] = useState<Document[]>([]); const [editing, setEditing] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("Loading OMS-102 scope...");
  const applyScope = useCallback((saved: Scope | null) => { setScope(saved); if (saved) { setForm({ componentFamily: saved.component_family, componentDescription: saved.component_description, serviceCategory: saved.service_category, connectionType: saved.connection_type, estimatedQuantity: saved.estimated_quantity === null ? "" : String(saved.estimated_quantity), additionalRequirements: saved.additional_requirements || "", customerSpecDocumentId: saved.customer_spec_document_id || "", customerConfirmed: saved.customer_confirmed, customerConfirmedBy: saved.customer_confirmed_by || "", customerConfirmedOn: saved.customer_confirmed_on || today }); setEditing(saved.status !== "Confirmed"); } onStatusChange(saved?.status === "Confirmed", true); }, [onStatusChange]);
  useEffect(() => { let active = true; void (async () => { try { const { data: auth } = await supabase.auth.getSession(); const token = auth.session?.access_token; if (!token) return window.location.assign("/login"); const response = await fetch(`/api/dti/job-scope?jobId=${encodeURIComponent(jobId)}`, { headers: { Authorization: `Bearer ${token}` } }); const body = await response.json() as Response; if (!response.ok) throw new Error(body.error || "TITAN could not load OMS-102 scope."); if (!active) return; setDocuments(body.documents ?? []); applyScope(body.scope ?? null); setMessage(""); } catch (error) { if (!active) return; setMessage(error instanceof Error ? error.message : "TITAN could not load OMS-102 scope."); onStatusChange(false, false); } })(); return () => { active = false; }; }, [jobId, applyScope, onStatusChange]);
  const update = (changes: Partial<typeof blank>) => setForm((current) => ({ ...current, ...changes }));
  async function save(action: "save" | "confirm") { if (saving) return; setSaving(true); setMessage(""); try { const { data: auth } = await supabase.auth.getSession(); const token = auth.session?.access_token; if (!token) return window.location.assign("/login"); const response = await fetch("/api/dti/job-scope", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ jobId, action, ...form }) }); const body = await response.json() as Response; if (!response.ok || !body.scope) throw new Error(body.error || "TITAN could not save OMS-102 scope."); applyScope(body.scope); setMessage(action === "confirm" ? "Customer-confirmed inspection scope saved." : "Scope draft saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "TITAN could not save OMS-102 scope."); } finally { setSaving(false); } }
  return <section className={styles.scopePanel} data-status={scope?.status || "Draft"}>
    <div className={styles.scopeHead}><div><span>OMS-102</span><h2>Service Category & Inspection Scope</h2><small>The customer sets the category. Titan derives the minimum DS-1 inspection package.</small></div><div><b>{scope?.status || "Not Confirmed"}</b>{scope?.status === "Confirmed" && !editing ? <button type="button" onClick={() => setEditing(true)}>Edit Scope</button> : null}</div></div>
    {message ? <div className={message.includes("saved") ? styles.success : styles.message}>{message}</div> : null}
    {editing ? <><div className={styles.scopeForm}>
      <label><span>Component Family</span><select value={form.componentFamily} onChange={(e) => update({ componentFamily: e.target.value })}><option>Drill Pipe</option><option>Work String Tubing</option><option>BHA / HWDP / Collars</option></select></label>
      <label><span>Component / Size / Grade</span><input value={form.componentDescription} onChange={(e) => update({ componentDescription: e.target.value })} /></label>
      <label><span>DS-1 Service Category</span><select value={form.serviceCategory} onChange={(e) => update({ serviceCategory: e.target.value })}><option value="">Select category</option><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option><option>HDLS</option></select></label>
      <label><span>Connection Type</span><select value={form.connectionType} onChange={(e) => update({ connectionType: e.target.value })}><option>API</option><option>Proprietary</option><option>Double-Shoulder</option><option>Other</option></select></label>
      <label><span>Estimated Quantity</span><input type="number" min="0" value={form.estimatedQuantity} onChange={(e) => update({ estimatedQuantity: e.target.value })} /></label>
      <label><span>Customer Specification</span><select value={form.customerSpecDocumentId} onChange={(e) => update({ customerSpecDocumentId: e.target.value })}><option value="">No attached specification</option>{documents.map((document) => <option key={document.id} value={document.id}>{document.document_type} / {document.display_name}</option>)}</select></label>
      <label className={styles.scopeWide}><span>Customer Additions / Tighter Requirements</span><textarea value={form.additionalRequirements} onChange={(e) => update({ additionalRequirements: e.target.value })} placeholder="Customer requirements may add to the baseline, never remove from it." /></label>
      <label><span>Customer Representative</span><input value={form.customerConfirmedBy} onChange={(e) => update({ customerConfirmedBy: e.target.value })} /></label>
      <label><span>Confirmation Date</span><input type="date" value={form.customerConfirmedOn} onChange={(e) => update({ customerConfirmedOn: e.target.value })} /></label>
      <label className={styles.scopeCheck}><input type="checkbox" checked={form.customerConfirmed} onChange={(e) => update({ customerConfirmed: e.target.checked })} /><span>Customer confirmed this service category and scope</span></label>
    </div><div className={styles.scopeActions}><button type="button" onClick={() => void save("save")} disabled={saving}>Save Draft</button><button className={styles.primary} type="button" onClick={() => void save("confirm")} disabled={saving}>{saving ? "Saving..." : "Confirm Scope"}</button></div></> : null}
    {scope?.baseline_scope?.length ? <div className={styles.scopeBaseline}><div><span>Required Baseline</span><strong>Category {scope.service_category} / {scope.component_family}</strong>{["Proprietary", "Double-Shoulder"].includes(scope.connection_type) ? <small>Dimensional 2 enforced for {scope.connection_type} connection.</small> : null}</div><ul>{scope.baseline_scope.map((item) => <li key={item}>{item}</li>)}</ul>{scope.additional_requirements ? <p><strong>Customer additions:</strong> {scope.additional_requirements}</p> : null}</div> : null}
  </section>;
}
