"use client";

import Image from "next/image";
import { useCallback, useEffect, useState } from "react";
import { dtiComponentLabel, dtiComponentTypes, resolveDtiReportComponentType, type DtiComponentType } from "../../../lib/dtiInspectionReport";
import { getDtiOfflineSnapshot, saveDtiOfflineSnapshot } from "../../../lib/dtiOfflineQueue";
import { goBackOrFallback } from "../../../lib/navigation";
import { supabase } from "../../../lib/supabase";
import styles from "./reports.module.css";

type Report = { id: string; report_number: string; operator_name: string; contractor_name: string | null; rig_number: string | null; report_date: string; field_invoice: string | null; inspection_scope: Record<string, unknown>; status: string; updated_at: string };
type Job = { id: string; job_number: string; title: string; customer_name: string | null; rig_name: string | null; lifecycle_status: string };
type ResponseData = { ok?: boolean; reports?: Report[]; jobs?: Job[]; report?: Report; archived?: boolean; error?: string };
const today = new Date().toISOString().slice(0, 10);
const snapshotKey = "inspection-report-list";
const empty = { componentType: "Drill Pipe" as DtiComponentType, jobId: "", operatorName: "", contractorName: "", rigNumber: "", reportDate: today, fieldInvoice: "", inspectionCrew: "", connectionSize: "", connectionType: "", grade: "", state: "" };

export default function DtiInspectionReportsPage() {
  const [reports, setReports] = useState<Report[]>([]); const [jobs, setJobs] = useState<Job[]>([]); const [form, setForm] = useState(empty); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("Loading inspection reports...");
  const load = useCallback(async () => { try { const { data } = await supabase.auth.getSession(); const token = data.session?.access_token; if (!token) { const cached = await getDtiOfflineSnapshot<ResponseData>(snapshotKey); if (cached && !navigator.onLine) { setReports(cached.data.reports ?? []); setJobs(cached.data.jobs ?? []); setMessage("Offline report list loaded."); return; } return window.location.assign("/login"); } const request = await fetch("/api/dti/inspection-reports", { headers: { Authorization: `Bearer ${token}` } }); const body = await request.json() as ResponseData; if (!request.ok) throw new Error(body.error || "TITAN could not load inspection reports."); setReports(body.reports ?? []); setJobs(body.jobs ?? []); setMessage(""); await saveDtiOfflineSnapshot(snapshotKey, body).catch(() => undefined); } catch (error) { const cached = await getDtiOfflineSnapshot<ResponseData>(snapshotKey).catch(() => null); if (cached) { setReports(cached.data.reports ?? []); setJobs(cached.data.jobs ?? []); setMessage("Offline report list loaded. Open a previously downloaded report to continue."); } else setMessage(error instanceof Error ? error.message : "TITAN could not load inspection reports."); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const update = (changes: Partial<typeof empty>) => setForm((current) => ({ ...current, ...changes }));
  function chooseJob(jobId: string) { const job = jobs.find((item) => item.id === jobId); update({ jobId, operatorName: job?.customer_name || form.operatorName, rigNumber: job?.rig_name || form.rigNumber }); }
  async function requestAction(payload: Record<string, unknown>) { const { data } = await supabase.auth.getSession(); const token = data.session?.access_token; if (!token) return window.location.assign("/login"); const request = await fetch("/api/dti/inspection-reports", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await request.json() as ResponseData; if (!request.ok) throw new Error(body.error || "TITAN could not save the inspection report."); return body; }
  async function createReport() { if (saving) return; setSaving(true); setMessage(""); try { const body = await requestAction({ action: "create-report", ...form }); if (body?.report?.id) window.location.assign(`/dti/inspection-reports/${encodeURIComponent(body.report.id)}`); } catch (error) { setMessage(error instanceof Error ? error.message : "TITAN could not create the inspection report."); } finally { setSaving(false); } }
  async function archiveReport(report: Report) { if (!window.confirm(`Archive ${report.report_number}? Its audit history will be retained.`)) return; setSaving(true); try { await requestAction({ action: "delete-report", reportId: report.id }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "TITAN could not archive the inspection report."); } finally { setSaving(false); } }
  return <main className={styles.page}>
    <header className={`${styles.header} titan-page-header`}><div className={styles.title}><Image src="/titan_logo.jpg" alt="TITAN" width={64} height={42} priority /><div><span>DTI Field Reporting</span><h1>Inspection Reports</h1></div></div><div className={styles.actions}><button type="button" onClick={() => goBackOrFallback("/service-lines/dti")}>Back</button><button type="button" onClick={() => void load()}>Refresh</button><button className={styles.primary} type="button" onClick={() => setOpen((value) => !value)}>{open ? "Close" : "New Report"}</button></div></header>
    {open ? <section className={styles.editor}><div className={styles.sectionHead}><div><span>New DTI Report</span><h2>Job Information</h2></div><small>A connected TITAN job is optional.</small></div><div className={styles.formGrid}>
      <label><span>Report Type</span><select value={form.componentType} onChange={(event) => update({ componentType: event.target.value as DtiComponentType })}>{dtiComponentTypes.map((type) => <option key={type} value={type}>{dtiComponentLabel(type)}</option>)}</select></label>
      <label className={styles.wide}><span>Connected Job (Optional)</span><select value={form.jobId} onChange={(event) => chooseJob(event.target.value)}><option value="">Manual job information</option>{jobs.map((job) => <option key={job.id} value={job.id}>{job.job_number} / {job.title} / {job.lifecycle_status}</option>)}</select></label>
      <label><span>Operator</span><input value={form.operatorName} onChange={(event) => update({ operatorName: event.target.value })} /></label><label><span>Contractor</span><input value={form.contractorName} onChange={(event) => update({ contractorName: event.target.value })} /></label><label><span>Rig Number</span><input value={form.rigNumber} onChange={(event) => update({ rigNumber: event.target.value })} /></label><label><span>Date</span><input type="date" value={form.reportDate} onChange={(event) => update({ reportDate: event.target.value })} /></label><label><span>Field Invoice</span><input value={form.fieldInvoice} onChange={(event) => update({ fieldInvoice: event.target.value })} /></label><label><span>Inspection Crew</span><input value={form.inspectionCrew} onChange={(event) => update({ inspectionCrew: event.target.value })} /></label><label><span>Connection Size</span><input value={form.connectionSize} onChange={(event) => update({ connectionSize: event.target.value })} /></label><label><span>Connection Type</span><input value={form.connectionType} onChange={(event) => update({ connectionType: event.target.value })} /></label><label><span>Grade</span><input value={form.grade} onChange={(event) => update({ grade: event.target.value })} /></label><label><span>State</span><input value={form.state} onChange={(event) => update({ state: event.target.value })} /></label><button className={styles.primary} type="button" onClick={() => void createReport()} disabled={saving}>{saving ? "Creating" : "Create Report"}</button>
    </div></section> : null}
    {message ? <div className={styles.message}>{message}</div> : null}
    <section className={styles.list}><div className={styles.sectionHead}><div><span>Active Records</span><h2>DTI Inspection Reports</h2></div><strong>{reports.length}</strong></div>{reports.map((report) => { const category = String(report.inspection_scope.inspectionCategory ?? ""); return <article key={report.id}><div><span>{report.report_number}</span><strong>{report.operator_name}</strong><small>{dtiComponentLabel(resolveDtiReportComponentType(report.inspection_scope))}{category ? ` / ${category === "HDLS" ? category : `Category ${category}`}` : ""} / {report.contractor_name || "No contractor"} / {report.rig_number || "No rig"}</small></div><div><span>Report Date</span><strong>{report.report_date}</strong><small>{report.field_invoice || "No field invoice"}</small></div><b data-status={report.status}>{report.status}</b><div className={styles.rowActions}><button type="button" onClick={() => window.location.assign(`/dti/inspection-reports/${encodeURIComponent(report.id)}`)}>Open</button><button type="button" onClick={() => void archiveReport(report)} disabled={saving}>Archive</button></div></article>; })}{!reports.length && !message ? <div className={styles.empty}>No DTI inspection reports have been created.</div> : null}</section>
  </main>;
}
