"use client";
import Image from "next/image";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import {goBackOrFallback} from "../../../lib/navigation";
import {supabase} from "../../../lib/supabase";
import styles from "./crew-schedule.module.css";

type Person={id:string;full_name:string;department:string|null}; type Job={id:string;job_number:string;title:string;customer_name:string|null;rig_name:string|null;lifecycle_status:string};
type Assignment={id:string;profile_id:string;job_id:string;assignment_role:string;starts_on:string;ends_on:string;status:string;notes:string|null};
type Data={assignments:Assignment[];people:Person[];jobs:Job[];error?:string};
const blank={id:"",profileId:"",jobId:"",assignmentRole:"Inspector",startsOn:"",endsOn:"",status:"Scheduled",notes:""};
function monthKey(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`;} function dateText(value:string){return new Date(`${value}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"});}

export default function CrewSchedule(){
 const [month,setMonth]=useState(()=>monthKey(new Date()));const [data,setData]=useState<Data|null>(null);const [message,setMessage]=useState("Loading crew schedule...");const [form,setForm]=useState<typeof blank|null>(null);const [saving,setSaving]=useState(false);const [search,setSearch]=useState("");
 const range=useMemo(()=>{const [year,part]=month.split("-").map(Number);const last=new Date(year,part,0);return{from:month+"-01",to:`${year}-${String(part).padStart(2,"0")}-${String(last.getDate()).padStart(2,"0")}`,days:Array.from({length:last.getDate()},(_,index)=>new Date(year,part-1,index+1))};},[month]);
 const load=useCallback(async()=>{setMessage("Loading crew schedule...");try{const {data:session}=await supabase.auth.getSession();const token=session.session?.access_token;if(!token)return window.location.assign("/login");const request=await fetch(`/api/dti/crew-schedule?from=${range.from}&to=${range.to}`,{headers:{Authorization:`Bearer ${token}`}});const body=await request.json() as Data;if(!request.ok)throw new Error(body.error||"TITAN could not load the crew schedule.");setData(body);setMessage("");}catch(error){setData(null);setMessage(error instanceof Error?error.message:"TITAN could not load the crew schedule.");}},[range.from,range.to]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
 const people=useMemo(()=>{const q=search.toLowerCase();return(data?.people??[]).filter(person=>!q||`${person.full_name} ${person.department}`.toLowerCase().includes(q));},[data,search]);
 const assignmentMap=useMemo(()=>new Map((data?.assignments??[]).map(item=>[item.id,item])),[data]);
 async function save(){if(!form)return;setSaving(true);try{const {data:session}=await supabase.auth.getSession();const request=await fetch("/api/dti/crew-schedule",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.session?.access_token||""}`},body:JSON.stringify(form)});const body=await request.json();if(!request.ok)throw new Error(body.error||"TITAN could not save this assignment.");setForm(null);await load();setMessage(body.warning||"Assignment saved.");}catch(error){setMessage(error instanceof Error?error.message:"TITAN could not save this assignment.");}finally{setSaving(false);}}
 async function remove(id:string){if(!window.confirm("Remove this assignment from the active schedule? Its history will be retained."))return;const {data:session}=await supabase.auth.getSession();const request=await fetch(`/api/dti/crew-schedule?id=${id}`,{method:"DELETE",headers:{Authorization:`Bearer ${session.session?.access_token||""}`}});if(request.ok){setForm(null);await load();}}
 function edit(item:Assignment){setForm({id:item.id,profileId:item.profile_id,jobId:item.job_id,assignmentRole:item.assignment_role,startsOn:item.starts_on,endsOn:item.ends_on,status:item.status,notes:item.notes||""});}
 function shift(amount:number){const [year,part]=month.split("-").map(Number);setMonth(monthKey(new Date(year,part-1+amount,1)));}
 return <main className={styles.shell}><header className={`${styles.header} titan-page-header`}><div className={styles.title}><Image src="/titan_logo.jpg" alt="TITAN" width={64} height={42}/><div><span>DTI</span><h1>Crew Schedule</h1></div></div><div className={styles.actions}><button onClick={()=>goBackOrFallback("/service-lines/dti")}>Back</button><Link href="/dti/competency">Competency</Link><button onClick={()=>setForm({...blank})}>Add Assignment</button></div></header>
 <section className={styles.toolbar}><button onClick={()=>shift(-1)} aria-label="Previous month">‹</button><input type="month" value={month} onChange={event=>setMonth(event.target.value)}/><button onClick={()=>shift(1)} aria-label="Next month">›</button><label><span>Search crew</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Name or service line"/></label></section>{message?<div className={styles.message}>{message}</div>:null}
 <section className={styles.calendar}><div className={styles.grid} style={{gridTemplateColumns:`minmax(190px,1.5fr) repeat(${range.days.length},minmax(34px,1fr))`}}><div className={styles.corner}>Crew member</div>{range.days.map(day=><div className={styles.day} key={day.toISOString()} data-weekend={day.getDay()===0||day.getDay()===6}><b>{day.toLocaleDateString(undefined,{weekday:"short"}).slice(0,1)}</b><span>{day.getDate()}</span></div>)}{people.map(person=><div className={styles.row} key={person.id} style={{gridColumn:`1 / span ${range.days.length+1}`,gridTemplateColumns:`subgrid`}}><div className={styles.person}><strong>{person.full_name}</strong><span>{person.department||"DTI"}</span></div>{range.days.map(day=>{const value=monthKey(day)+`-${String(day.getDate()).padStart(2,"0")}`;const matches=(data?.assignments??[]).filter(item=>item.profile_id===person.id&&item.starts_on<=value&&item.ends_on>=value);return <div className={styles.cell} key={value} data-weekend={day.getDay()===0||day.getDay()===6}>{matches.map(item=>{const job=data?.jobs.find(row=>row.id===item.job_id);return <button key={item.id} data-status={item.status} title={`${job?.job_number||"Job"} / ${job?.title||""}`} onClick={()=>edit(assignmentMap.get(item.id)!)}>{item.starts_on===value?(job?.job_number||"Job"):""}</button>})}</div>;})}</div>)}</div></section>
 <section className={styles.history}><h2>Assignment History</h2>{(data?.assignments??[]).map(item=>{const person=data?.people.find(row=>row.id===item.profile_id);const job=data?.jobs.find(row=>row.id===item.job_id);return <button key={item.id} onClick={()=>edit(item)}><strong>{person?.full_name}</strong><span>{job?.job_number} / {job?.title}</span><span>{dateText(item.starts_on)} - {dateText(item.ends_on)}</span><b>{item.status}</b></button>})}</section>
 {form?<div className={styles.backdrop}><section className={styles.modal}><div className={styles.modalHead}><div><span>DTI Crew</span><h2>{form.id?"Edit Assignment":"Add Assignment"}</h2></div><button onClick={()=>setForm(null)} aria-label="Close">X</button></div><div className={styles.form}><label><span>Person</span><select value={form.profileId} onChange={event=>setForm({...form,profileId:event.target.value})}><option value="">Select person</option>{(data?.people??[]).map(person=><option key={person.id} value={person.id}>{person.full_name}</option>)}</select></label><label><span>DTI Job</span><select value={form.jobId} onChange={event=>setForm({...form,jobId:event.target.value})}><option value="">Select job</option>{(data?.jobs??[]).map(job=><option key={job.id} value={job.id}>{job.job_number} / {job.title}</option>)}</select></label><label><span>Role</span><select value={form.assignmentRole} onChange={event=>setForm({...form,assignmentRole:event.target.value})}>{["Lead Inspector","Inspector","Level 2 Inspector","Support"].map(value=><option key={value}>{value}</option>)}</select></label><label><span>Status</span><select value={form.status} onChange={event=>setForm({...form,status:event.target.value})}>{["Scheduled","Confirmed","Complete","Cancelled"].map(value=><option key={value}>{value}</option>)}</select></label><label><span>Starts</span><input type="date" value={form.startsOn} onChange={event=>setForm({...form,startsOn:event.target.value})}/></label><label><span>Ends</span><input type="date" value={form.endsOn} onChange={event=>setForm({...form,endsOn:event.target.value})}/></label><label className={styles.full}><span>Notes</span><textarea value={form.notes} onChange={event=>setForm({...form,notes:event.target.value})}/></label></div><div className={styles.modalActions}>{form.id?<button onClick={()=>void remove(form.id)}>Remove</button>:null}<button onClick={()=>setForm(null)}>Cancel</button><button className={styles.primary} disabled={saving||!form.profileId||!form.jobId||!form.startsOn||!form.endsOn} onClick={()=>void save()}>{saving?"Saving...":"Save Assignment"}</button></div></section></div>:null}</main>;
}
