"use client";

import Image from "next/image";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import DtiProcedureMenu from "../../../components/DtiProcedureMenu";
import { goBackOrFallback } from "../../../../lib/navigation";
import { supabase } from "../../../../lib/supabase";
import styles from "./jobCloseout.module.css";

/* eslint-disable @typescript-eslint/no-explicit-any */

type Row = Record<string, any>;
type Gate = { key: string; label: string; passed: boolean; detail: string };
type ApiResponse = { ok?: boolean; error?: string; job?: Row; runs?: Row[]; run?: Row | null; racks?: Row[]; calibrations?: Row[]; summary?: Row | null; debrief?: Row | null; deviations?: Row[]; debriefCounts?: { borderline: number; deviationAgreements: number }; totals?: { completedJoints: number; completeRacks: number; rackCount: number }; gates?: Gate[]; ready?: boolean };
type Station = { station: string; status: string; driver: string };
type ActionItem = { lesson: string; owner: string; dueDate: string };
type DebriefForm = { onPlan: string; crewSize: string; weatherConditions: string; loaderCyclesStandbyTime: string; stationPerformance: Station[]; slowdownCategories: string[]; stationBehind: string; varianceDriver: string; wentWell: string; slowedBy: string; equipmentFailures: string; equipmentTaggedOut: string; restockConsumables: string; kpaCompleted: string; restockListGenerated: string; nearMissGoodCatch: string; stopWorkUsed: string; stopWorkDescription: string; jsaEffective: string; jsaUpdateNeeded: string; safetyObservations: string; grayAreaSummary: string; borderlineCount: string; deviationAgreementsAttached: boolean; customerFeedback: string; repeatIssue: boolean; repeatNote: string; lessonsLearned: string; actionOwnerName: string; actionItems: ActionItem[]; crewLeadSignoffName: string; crewLeadSignedOn: string; managerReviewName: string; managerReviewedOn: string };

const stationNames = ["Tube Prep", "Connection Clean", "Inspect & Reface", "Dimensional", "EMI", "Setup / Teardown"];
const blankStations = () => stationNames.map((station) => ({ station, status: "", driver: "" }));
const blankActions = (): ActionItem[] => [{ lesson: "", owner: "", dueDate: "" }];
const emptyDebrief: DebriefForm = { onPlan: "", crewSize: "", weatherConditions: "", loaderCyclesStandbyTime: "", stationPerformance: blankStations(), slowdownCategories: [], stationBehind: "", varianceDriver: "", wentWell: "", slowedBy: "", equipmentFailures: "", equipmentTaggedOut: "", restockConsumables: "", kpaCompleted: "", restockListGenerated: "", nearMissGoodCatch: "", stopWorkUsed: "", stopWorkDescription: "", jsaEffective: "", jsaUpdateNeeded: "", safetyObservations: "", grayAreaSummary: "", borderlineCount: "0", deviationAgreementsAttached: false, customerFeedback: "", repeatIssue: false, repeatNote: "", lessonsLearned: "", actionOwnerName: "", actionItems: blankActions(), crewLeadSignoffName: "", crewLeadSignedOn: "", managerReviewName: "", managerReviewedOn: "" };
function mapDebrief(row?: Row | null): DebriefForm { if (!row) return { ...emptyDebrief, stationPerformance: blankStations(), actionItems: blankActions() }; const stations = Array.isArray(row.station_performance) ? row.station_performance : []; const actions = Array.isArray(row.action_items) && row.action_items.length ? row.action_items : blankActions(); return { onPlan: row.on_plan === null ? "" : String(Boolean(row.on_plan)), crewSize: row.crew_size ? String(row.crew_size) : "", weatherConditions: row.weather_conditions || "", loaderCyclesStandbyTime: row.loader_cycles_standby_time || "", stationPerformance: stationNames.map((station) => stations.find((item: Station) => item.station === station) || { station, status: "", driver: "" }), slowdownCategories: Array.isArray(row.slowdown_categories) ? row.slowdown_categories : [], stationBehind: row.station_behind || "", varianceDriver: row.variance_driver || "", wentWell: row.went_well || "", slowedBy: row.slowed_by || "", equipmentFailures: row.equipment_failures || "", equipmentTaggedOut: row.equipment_tagged_out || "", restockConsumables: row.restock_consumables || "", kpaCompleted: row.kpa_completed === null ? "" : String(Boolean(row.kpa_completed)), restockListGenerated: row.restock_list_generated === null ? "" : String(Boolean(row.restock_list_generated)), nearMissGoodCatch: row.near_miss_good_catch || "", stopWorkUsed: row.stop_work_used === null ? "" : String(Boolean(row.stop_work_used)), stopWorkDescription: row.stop_work_description || "", jsaEffective: row.jsa_effective === null ? "" : String(Boolean(row.jsa_effective)), jsaUpdateNeeded: row.jsa_update_needed || "", safetyObservations: row.safety_observations || "", grayAreaSummary: row.gray_area_summary || "", borderlineCount: String(row.borderline_count ?? 0), deviationAgreementsAttached: Boolean(row.deviation_agreements_attached), customerFeedback: row.customer_feedback || "", repeatIssue: Boolean(row.repeat_issue), repeatNote: row.repeat_note || "", lessonsLearned: row.lessons_learned || "", actionOwnerName: row.action_owner_name || "", actionItems: actions, crewLeadSignoffName: row.crew_lead_signoff_name || "", crewLeadSignedOn: row.crew_lead_signed_on || "", managerReviewName: row.manager_review_name || "", managerReviewedOn: row.manager_reviewed_on || "" }; }

export default function DtiJobCloseoutPage() {
  const params = useParams<{ jobId: string }>(); const jobId = String(params.jobId ?? "");
  const [data, setData] = useState<ApiResponse | null>(null); const [form, setForm] = useState<DebriefForm>(emptyDebrief); const [message, setMessage] = useState("Loading DTI closeout..."); const [saving, setSaving] = useState(false);

  const load = useCallback(async (runId = "") => {
    setMessage("Loading DTI closeout...");
    try { const { data: auth } = await supabase.auth.getSession(); const token = auth.session?.access_token; if (!token) return window.location.assign("/login"); const response = await fetch(`/api/dti/job-closeout?jobId=${encodeURIComponent(jobId)}${runId ? `&runId=${encodeURIComponent(runId)}` : ""}`, { headers: { Authorization: `Bearer ${token}` } }); const body = await response.json() as ApiResponse; if (!response.ok) throw new Error(body.error || "TITAN could not load DTI closeout."); setData(body); setForm(mapDebrief(body.debrief)); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "TITAN could not load DTI closeout."); }
  }, [jobId]);
  useEffect(() => { if (!jobId) return; const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [jobId, load]);

  async function send(payload: Record<string, unknown>, success: string) {
    if (saving) return null; setSaving(true); setMessage("");
    try { const { data: auth } = await supabase.auth.getSession(); const token = auth.session?.access_token; if (!token) { window.location.assign("/login"); return null; } const response = await fetch("/api/dti/job-closeout", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ jobId, runId: data?.run?.id, ...payload }) }); const body = await response.json() as ApiResponse; if (!response.ok) throw new Error(body.error || "TITAN could not save DTI closeout."); setData(body); setForm(mapDebrief(body.debrief)); setMessage(success); return body; } catch (error) { setMessage(error instanceof Error ? error.message : "TITAN could not save DTI closeout."); return null; } finally { setSaving(false); }
  }
  async function createSummary() { const result = await send({ action: "create-summary" }, "Daily Summary draft is ready."); if (result?.summary?.id) window.location.assign(`/dti-summary?summaryId=${encodeURIComponent(result.summary.id)}`); }
  const update = (changes: Partial<DebriefForm>) => setForm((current) => ({ ...current, ...changes }));
  const updateStation = (index: number, changes: Partial<Station>) => update({ stationPerformance: form.stationPerformance.map((item, itemIndex) => itemIndex === index ? { ...item, ...changes } : item) });
  const toggleSlowdown = (category: string) => update({ slowdownCategories: form.slowdownCategories.includes(category) ? form.slowdownCategories.filter((item) => item !== category) : [...form.slowdownCategories, category] });
  const updateAction = (index: number, changes: Partial<ActionItem>) => update({ actionItems: form.actionItems.map((item, itemIndex) => itemIndex === index ? { ...item, ...changes } : item) });
  const complete = data?.debrief?.completion_status === "Complete";

  return <main className={styles.page}>
    <header className={`${styles.header} titan-page-header`}><div className={styles.title}><Image src="/titan_logo.jpg" alt="TITAN" width={64} height={42} priority /><div><span>DTI / OMS-203</span><h1>Job Closeout</h1></div></div><div className={styles.headerActions}><button type="button" onClick={() => goBackOrFallback("/dti?view=jobs")}>Back</button>{data?.job ? <Link href={`/dti/job-execution/${encodeURIComponent(data.job.id)}`}>Execution</Link> : null}<Link href="/dti/deviations">Deviations</Link><Link href="/dti-summary">Daily Summaries</Link><DtiProcedureMenu procedures={[{ documentNumber: "OMS-203", label: "Post-Job Review" }, { documentNumber: "OMS-104", label: "Per-Rack Workflow" }, { documentNumber: "OMS-202", label: "Deviation Agreement" }]} /><button type="button" onClick={() => void load(data?.run?.id)}>Refresh</button></div></header>
    {data?.job ? <section className={styles.jobBand}><div><span>{data.job.job_number} / {data.job.lifecycle_status}</span><h2>{data.job.title}</h2><small>{data.job.customer_name || "No customer"} / {data.job.rig_name || "No rig"}</small></div><b data-ready={data.ready}>{data.ready ? "Closeout Ready" : "Closeout Incomplete"}</b></section> : null}
    {message ? <div className={message.includes("ready") || message.includes("saved") ? styles.success : styles.message}>{message}</div> : null}
    {data?.run ? <><section className={styles.runBar}><label><span>Execution Run</span><select value={data.run.id} onChange={(event) => void load(event.target.value)}>{data.runs?.map((run) => <option key={run.id} value={run.id}>{run.run_date} / {run.shift_name} / {run.status}</option>)}</select></label><div><span>Completed Joints</span><strong>{data.totals?.completedJoints ?? 0}</strong></div><div><span>Racks</span><strong>{data.totals?.completeRacks ?? 0} / {data.totals?.rackCount ?? 0}</strong></div></section>
      <section className={styles.gates}><div className={styles.sectionHead}><div><span>Closeout Control</span><h2>Readiness</h2></div><strong>{data.gates?.filter((gate) => gate.passed).length ?? 0} / {data.gates?.length ?? 0}</strong></div><div className={styles.gateGrid}>{data.gates?.map((gate) => <article key={gate.key} data-passed={gate.passed}><span aria-hidden="true">{gate.passed ? "OK" : "OPEN"}</span><div><strong>{gate.label}</strong><small>{gate.detail}</small></div></article>)}</div></section>
      <section className={styles.summaryPanel}><div><span>DTI Daily Summary</span><h2>{data.summary?.summary_number || "Create from completed execution"}</h2><p>The execution rollup seeds the job, rack descriptions, inspector, and completed joints. Inspection results remain editable on the standard summary.</p></div>{data.summary ? <Link className={styles.primary} href={`/dti-summary?summaryId=${encodeURIComponent(data.summary.id)}`}>Open Summary</Link> : <button className={styles.primary} type="button" disabled={saving || data.run.status !== "Complete"} onClick={() => void createSummary()}>Create Daily Summary</button>}</section>
      <section className={styles.debrief}><div className={styles.sectionHead}><div><span>OMS-203</span><h2>Post-Job Debrief &amp; Lessons Learned</h2></div><div className={styles.debriefIdentity}>{data.debrief?.debrief_number ? <strong>{data.debrief.debrief_number}</strong> : null}<b data-complete={complete}>{complete ? "Complete" : "Draft"}</b></div></div>
      <fieldset disabled={complete || saving}><legend>1. Job Summary</legend><div className={styles.formGrid}><label><span>Crew Size</span><input type="number" min="1" value={form.crewSize} onChange={(e) => update({ crewSize: e.target.value })} /></label><label><span>Weather / Conditions</span><input value={form.weatherConditions} onChange={(e) => update({ weatherConditions: e.target.value })} /></label><label><span>Job Completed on Plan?</span><select value={form.onPlan} onChange={(e) => update({ onPlan: e.target.value })}><option value="">Select</option><option value="true">Yes</option><option value="false">No</option></select></label><label><span>Loader Cycles / Standby Time</span><input value={form.loaderCyclesStandbyTime} onChange={(e) => update({ loaderCyclesStandbyTime: e.target.value })} /></label></div></fieldset>
      <fieldset disabled={complete || saving}><legend>2. Performance vs. Plan</legend><div className={styles.stationTable}><div className={styles.stationHeader}><span>Phase / Station</span><span>vs. Benchmark</span><span>Variance Driver</span></div>{form.stationPerformance.map((item, index) => <div key={item.station} className={styles.stationRow}><strong>{item.station}</strong><select value={item.status} onChange={(e) => updateStation(index, { status: e.target.value })}><option value="">Select</option><option>Ahead</option><option>On</option><option>Behind</option></select><input value={item.driver} onChange={(e) => updateStation(index, { driver: e.target.value })} placeholder={item.status === "Behind" ? "Required: what drove the variance" : "Optional note"} /></div>)}</div><div className={styles.formGrid}><label><span>Station Behind / Bottleneck</span><input value={form.stationBehind} onChange={(e) => update({ stationBehind: e.target.value })} /></label><label><span>Overall Variance Driver</span><input value={form.varianceDriver} onChange={(e) => update({ varianceDriver: e.target.value })} /></label></div></fieldset>
      <fieldset disabled={complete || saving}><legend>3. What Went Well</legend><div className={styles.formGrid}><label className={styles.wide}><span>Practices to Keep</span><textarea value={form.wentWell} onChange={(e) => update({ wentWell: e.target.value })} /></label></div></fieldset>
      <fieldset disabled={complete || saving}><legend>4. What Slowed Us Down</legend><div className={styles.choiceGrid}>{["Scope / Category Unclear", "Customer Spec Not on Hand", "Equipment Issue", "Setup / Space", "Consumables Short", "Loader Availability", "Weather", "Crew / Staffing", "Other"].map((item) => <label key={item}><input type="checkbox" checked={form.slowdownCategories.includes(item)} onChange={() => toggleSlowdown(item)} /><span>{item}</span></label>)}</div><div className={styles.formGrid}><label className={styles.wide}><span>What Happened and What Would Prevent It</span><textarea value={form.slowedBy} onChange={(e) => update({ slowedBy: e.target.value })} /></label></div></fieldset>
      <fieldset disabled={complete || saving}><legend>5. Equipment &amp; Calibration</legend><div className={styles.formGrid}><label className={styles.wide}><span>Equipment Failures / Issues</span><textarea value={form.equipmentFailures} onChange={(e) => update({ equipmentFailures: e.target.value })} placeholder="Enter None when there were no issues" /></label><label><span>Tagged Out of Service</span><input value={form.equipmentTaggedOut} onChange={(e) => update({ equipmentTaggedOut: e.target.value })} placeholder="Asset or None" /></label><label><span>Restock / Consumables Flagged</span><input value={form.restockConsumables} onChange={(e) => update({ restockConsumables: e.target.value })} placeholder="Items or None" /></label><label><span>KPA Completed on Unit?</span><select value={form.kpaCompleted} onChange={(e) => update({ kpaCompleted: e.target.value })}><option value="">Select</option><option value="true">Yes</option><option value="false">No</option></select></label><label><span>Restock List Generated?</span><select value={form.restockListGenerated} onChange={(e) => update({ restockListGenerated: e.target.value })}><option value="">Select</option><option value="true">Yes</option><option value="false">No</option></select></label></div></fieldset>
      <fieldset disabled={complete || saving}><legend>6. Safety Observations</legend><div className={styles.formGrid}><label className={styles.wide}><span>Near Miss / Good Catch</span><textarea value={form.nearMissGoodCatch} onChange={(e) => update({ nearMissGoodCatch: e.target.value })} placeholder="Enter None when there were no observations" /></label><label><span>Stop-Work Used?</span><select value={form.stopWorkUsed} onChange={(e) => update({ stopWorkUsed: e.target.value })}><option value="">Select</option><option value="false">No</option><option value="true">Yes</option></select></label>{form.stopWorkUsed === "true" ? <label className={styles.wide}><span>Stop-Work Description</span><textarea value={form.stopWorkDescription} onChange={(e) => update({ stopWorkDescription: e.target.value })} /></label> : null}<label><span>JSA Effective?</span><select value={form.jsaEffective} onChange={(e) => update({ jsaEffective: e.target.value })}><option value="">Select</option><option value="true">Yes</option><option value="false">Needs Update</option></select></label>{form.jsaEffective === "false" ? <label className={styles.wide}><span>JSA Update Needed</span><textarea value={form.jsaUpdateNeeded} onChange={(e) => update({ jsaUpdateNeeded: e.target.value })} /></label> : null}<label className={styles.wide}><span>Additional Safety Observations</span><textarea value={form.safetyObservations} onChange={(e) => update({ safetyObservations: e.target.value })} /></label></div></fieldset>
      <fieldset disabled={complete || saving}><legend>7. Decisions &amp; Escalations</legend><div className={styles.autoCounts}><div><span>Borderline Calls</span><strong>{data.debriefCounts?.borderline ?? 0}</strong></div><div><span>Approved OMS-202 Agreements</span><strong>{data.debriefCounts?.deviationAgreements ?? 0}</strong></div></div>{(data.debriefCounts?.deviationAgreements ?? 0) > 0 ? <label className={styles.confirmCheck}><input type="checkbox" checked={form.deviationAgreementsAttached} onChange={(e) => update({ deviationAgreementsAttached: e.target.checked })} /><span>All OMS-202 agreements completed and attached</span></label> : null}<div className={styles.formGrid}><label className={styles.wide}><span>Gray-Area Decision Summary</span><textarea value={form.grayAreaSummary} onChange={(e) => update({ grayAreaSummary: e.target.value })} /></label></div></fieldset>
      <fieldset disabled={complete || saving}><legend>8. Customer / Third-Party Feedback</legend><div className={styles.formGrid}><label className={styles.wide}><span>Feedback</span><textarea value={form.customerFeedback} onChange={(e) => update({ customerFeedback: e.target.value })} /></label><label className={styles.check}><input type="checkbox" checked={form.repeatIssue} onChange={(e) => update({ repeatIssue: e.target.checked })} /><span>Repeated issue identified</span></label>{form.repeatIssue ? <label className={styles.wide}><span>Repeated Issue for Trend Tracking</span><textarea value={form.repeatNote} onChange={(e) => update({ repeatNote: e.target.value })} /></label> : null}</div></fieldset>
      <fieldset disabled={complete || saving}><legend>9. Lessons Learned &amp; Action Items</legend><div className={styles.formGrid}><label className={styles.wide}><span>What We Would Do Differently Next Time</span><textarea value={form.lessonsLearned} onChange={(e) => update({ lessonsLearned: e.target.value })} /></label></div><div className={styles.actionTable}>{form.actionItems.map((item, index) => <div key={index}><input value={item.lesson} onChange={(e) => updateAction(index, { lesson: e.target.value })} placeholder="Lesson / action item" /><input value={item.owner} onChange={(e) => updateAction(index, { owner: e.target.value })} placeholder="Owner" /><input type="date" value={item.dueDate} onChange={(e) => updateAction(index, { dueDate: e.target.value })} /><button type="button" aria-label="Remove action item" onClick={() => update({ actionItems: form.actionItems.filter((_, itemIndex) => itemIndex !== index) })}>X</button></div>)}</div><button type="button" className={styles.addAction} onClick={() => update({ actionItems: [...form.actionItems, { lesson: "", owner: "", dueDate: "" }] })}>Add Action Item</button></fieldset>
      <fieldset disabled={complete || saving}><legend>10. Sign-Off</legend><div className={styles.formGrid}><label><span>Crew Lead</span><input value={form.crewLeadSignoffName} onChange={(e) => update({ crewLeadSignoffName: e.target.value })} /></label><label><span>Date</span><input type="date" value={form.crewLeadSignedOn} onChange={(e) => update({ crewLeadSignedOn: e.target.value })} /></label><label><span>Superintendent / Service Line Manager</span><input value={form.managerReviewName} onChange={(e) => update({ managerReviewName: e.target.value })} /></label><label><span>Date</span><input type="date" value={form.managerReviewedOn} onChange={(e) => update({ managerReviewedOn: e.target.value })} /></label></div></fieldset>
      <div className={styles.debriefActions}>{complete ? <span>OMS-203 closeout completed {data.debrief?.finalized_at ? new Date(data.debrief.finalized_at).toLocaleString() : ""}.</span> : <><button type="button" disabled={saving} onClick={() => void send({ action: "save-debrief", ...form, finalize: false }, "OMS-203 draft saved.")}>Save Draft</button><button className={styles.primary} type="button" disabled={saving} onClick={() => void send({ action: "save-debrief", ...form, finalize: true }, "OMS-203 closeout completed.")}>{saving ? "Saving..." : "Complete Closeout"}</button></>}</div></section>
      {data.deviations?.length ? <section className={styles.deviations}><h2>Open Deviations</h2>{data.deviations.map((item) => <div key={item.id}><strong>{item.deviation_number}</strong><span>{item.defect_type}</span><b>{item.status}</b></div>)}</section> : null}
    </> : data && !message ? <div className={styles.empty}>No DTI execution run has been recorded for this job.</div> : null}
  </main>;
}
