"use client";

import { useState } from "react";
import { supabase } from "../../../../lib/supabase";
import styles from "./jobExecution.module.css";

type Rack = { id: string; rack_number: number; rack_name: string | null };
export type DefectDecision = { id: string; decision_number: string; rack_run_id: string | null; joint_ids: string; quantity: number; defect_type: string; component_location: string; detection_method: string; confirmation_method: string; measurements: string; controlling_criteria: string; disposition: string; inspector_name: string; created_at: string };
type Props = { jobId: string; runId: string; racks: Rack[]; decisions: DefectDecision[]; onSaved: () => void };
const blank = { rackId: "", jointIds: "", quantity: "1", defectType: "", componentLocation: "", detectionMethod: "", confirmationMethod: "", measurements: "", controllingCriteria: "", disposition: "", actionNotes: "", inspectorName: "" };

export default function DtiDefectDecisionPanel({ jobId, runId, racks, decisions, onSaved }: Props) {
  const [open, setOpen] = useState(false); const [form, setForm] = useState(blank); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const update = (changes: Partial<typeof blank>) => setForm((current) => ({ ...current, ...changes }));
  async function save() { if (saving) return; setSaving(true); setMessage(""); try { const { data: auth } = await supabase.auth.getSession(); const token = auth.session?.access_token; if (!token) return window.location.assign("/login"); const response = await fetch("/api/dti/job-execution", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ action: "save-defect", jobId, runId, ...form }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "TITAN could not record the defect decision."); setForm({ ...blank, inspectorName: form.inspectorName }); setOpen(false); setMessage("Defect decision recorded."); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : "TITAN could not record the defect decision."); } finally { setSaving(false); } }
  return <section className={styles.defects}>
    <div className={styles.panelHead}><div><span>OMS-105</span><h2>Defect Decisions</h2></div><div className={styles.rowActions}><strong>{decisions.length} records</strong><button className={styles.primary} type="button" onClick={() => setOpen((value) => !value)}>{open ? "Cancel" : "Record Defect"}</button></div></div>
    {message ? <div className={message.includes("recorded") ? styles.onTrack : styles.message}>{message}</div> : null}
    {open ? <div className={styles.defectForm}><div className={styles.decisionFlow}><b>Detect</b><span>then</span><b>Confirm independently</b><span>then</span><b>Measure</b><span>then</span><b>Apply criteria</b><span>then</span><b>Disposition</b></div><div className={styles.formGrid}>
      <label><span>Rack</span><select value={form.rackId} onChange={(e) => update({ rackId: e.target.value })}><option value="">Whole job / no rack</option>{racks.map((rack) => <option key={rack.id} value={rack.id}>Rack {rack.rack_number} / {rack.rack_name || "Unnamed"}</option>)}</select></label>
      <label><span>Joint / Component IDs</span><input value={form.jointIds} onChange={(e) => update({ jointIds: e.target.value })} /></label>
      <label><span>Quantity</span><input type="number" min="1" value={form.quantity} onChange={(e) => update({ quantity: e.target.value })} /></label>
      <label><span>Defect Type</span><select value={form.defectType} onChange={(e) => update({ defectType: e.target.value, disposition: ["Fatigue Crack", "Stress Crack", "Cracked Connection", "Bent Pipe", "Structural Drift Failure"].includes(e.target.value) ? "Reject" : form.disposition })}><option value="">Select</option><option>Fatigue Crack</option><option>Stress Crack</option><option>Cracked Connection</option><option>Bent Pipe</option><option>Structural Drift Failure</option><option>Removable Drift Blockage</option><option>General Wall Loss</option><option>Pitting</option><option>Gouge / Cut</option><option>Slip / Tong Damage</option><option>Thread Damage</option><option>Hardband Cracking</option><option>Ovality</option><option>Minimum Tong</option><option>TSTR</option><option>EMI Indication</option><option>Minimum Wall</option><option>Other</option></select></label>
      <label><span>Component Location</span><select value={form.componentLocation} onChange={(e) => update({ componentLocation: e.target.value })}><option value="">Select</option><option>Tube Body</option><option>Slip Area</option><option>Upset / Transition</option><option>Tool Joint / Threads - Pin</option><option>Tool Joint / Threads - Box</option><option>Seal / Shoulder - Pin</option><option>Seal / Shoulder - Box</option><option>BHA High-Load</option><option>Other</option></select></label>
      <label><span>Detection Method</span><select value={form.detectionMethod} onChange={(e) => update({ detectionMethod: e.target.value })}><option value="">Select</option><option>Visual</option><option>EMI</option><option>UT</option><option>MPI</option><option>PT</option><option>OD Gauge</option><option>Drift</option><option>Thread Gauge</option></select></label>
      <label><span>Independent Confirmation</span><select value={form.confirmationMethod} onChange={(e) => update({ confirmationMethod: e.target.value })}><option value="">Select a second method</option><option>Visual</option><option>EMI</option><option>UT</option><option>MPI</option><option>PT</option><option>OD Gauge</option><option>Drift</option><option>Thread Gauge</option><option>Measurement</option></select></label>
      <label><span>Final Disposition</span><select value={form.disposition} onChange={(e) => update({ disposition: e.target.value })}><option value="">Select</option><option>Accept</option><option>Reject</option><option>DBR</option><option>Field Repair</option><option>Reface</option><option>Hardband</option></select></label>
      <label className={styles.wide}><span>Measurements / Severity</span><textarea value={form.measurements} onChange={(e) => update({ measurements: e.target.value })} /></label>
      <label className={styles.wide}><span>Controlling Criteria</span><input value={form.controllingCriteria} onChange={(e) => update({ controllingCriteria: e.target.value })} placeholder="Customer specification / DS-1 / API section and limit" /></label>
      <label className={styles.wide}><span>Action Notes</span><textarea value={form.actionNotes} onChange={(e) => update({ actionNotes: e.target.value })} /></label>
      <label><span>Inspector</span><input value={form.inspectorName} onChange={(e) => update({ inspectorName: e.target.value })} /></label>
    </div><div className={styles.defectActions}><span>Borderline or outside-standard acceptance belongs in OMS-109.</span><button className={styles.primary} type="button" onClick={() => void save()} disabled={saving}>{saving ? "Saving..." : "Save Decision"}</button></div></div> : null}
    <div className={styles.defectList}>{decisions.map((item) => <article key={item.id} data-disposition={item.disposition}><div><span>{item.decision_number}</span><strong>{item.defect_type}</strong><small>{item.joint_ids} / Qty {item.quantity}</small></div><div><span>Confirmed</span><strong>{item.detection_method} + {item.confirmation_method}</strong><small>{item.measurements}</small></div><div><span>Criteria</span><strong>{item.controlling_criteria}</strong><small>{item.component_location}</small></div><b>{item.disposition}</b></article>)}</div>
    {!decisions.length ? <div className={styles.empty}>No confirmed defect decisions recorded for this run.</div> : null}
  </section>;
}
