"use client";

import { useState } from "react";
import { supabase } from "../../../../lib/supabase";
import type { DefectDecision } from "./DtiDefectDecisionPanel";
import type { TubularSpec } from "./DtiDimensionalPanel";
import styles from "./jobExecution.module.css";

type Rack = { id: string; rack_number: number; rack_name: string | null };
export type JointInspection = { id: string; inspection_number: string; rack_run_id: string; tubular_spec_id: string; joint_id: string; serial_number: string | null; wall_basis: string; ut_lowest_wall_inches: number | null; ut_minimum_inches: number | null; ut_result: string; emi_result: string; emi_indication_description: string | null; visual_result: string; mpi_result: string; connection_result: string; dimensional_evidence_count: number; source_defect_decision_id: string | null; final_disposition: string; decision_justification: string; record_status: string; inspector_name: string; inspected_at: string; notes: string | null };
type Props = { jobId: string; runId: string; racks: Rack[]; specs: TubularSpec[]; decisions: DefectDecision[]; records: JointInspection[]; onSaved: () => void };
const now = () => { const date = new Date(); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 16); };
const blank = { rackId: "", specId: "", jointId: "", serialNumber: "", wallBasis: "Premium", utLowestWallInches: "", emiResult: "Pass", emiIndicationDescription: "", visualResult: "Pass", mpiResult: "Pass", connectionResult: "Pass", sourceDefectDecisionId: "", decisionJustification: "All required inspections passed within the controlled acceptance criteria.", inspectorName: "", inspectedAt: now(), notes: "" };

export default function DtiJointInspectionPanel({ jobId, runId, racks, specs, decisions, records, onSaved }: Props) {
  const [open, setOpen] = useState(false); const [form, setForm] = useState(blank); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const update = (changes: Partial<typeof blank>) => setForm((current) => ({ ...current, ...changes }));
  function edit(item: JointInspection) { setForm({ rackId: item.rack_run_id, specId: item.tubular_spec_id, jointId: item.joint_id, serialNumber: item.serial_number || "", wallBasis: item.wall_basis, utLowestWallInches: item.ut_lowest_wall_inches === null ? "" : String(item.ut_lowest_wall_inches), emiResult: item.emi_result, emiIndicationDescription: item.emi_indication_description || "", visualResult: item.visual_result, mpiResult: item.mpi_result, connectionResult: item.connection_result, sourceDefectDecisionId: item.source_defect_decision_id || "", decisionJustification: item.decision_justification, inspectorName: item.inspector_name, inspectedAt: item.inspected_at.slice(0, 16), notes: item.notes || "" }); setOpen(true); document.getElementById("joint-inspection-form")?.scrollIntoView({ behavior: "smooth", block: "start" }); }
  async function save() { if (saving) return; setSaving(true); setMessage(""); try { const { data: auth } = await supabase.auth.getSession(); const token = auth.session?.access_token; if (!token) return window.location.assign("/login"); const response = await fetch("/api/dti/job-execution", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ action: "save-joint-inspection", jobId, runId, ...form }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "TITAN could not save the joint inspection."); const numeric = /^\d+$/.test(form.jointId) ? String(Number(form.jointId) + 1) : ""; setForm({ ...blank, rackId: form.rackId, specId: form.specId, jointId: numeric, inspectorName: form.inspectorName, inspectedAt: now() }); setMessage("Joint inspection saved and evaluated."); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : "TITAN could not save the joint inspection."); } finally { setSaving(false); } }
  return <section className={styles.jointInspections}>
    <div className={styles.panelHead}><div><span>IOM 13.2</span><h2>Joint Inspection Register</h2></div><div className={styles.rowActions}><strong>{records.length} joints</strong><button className={styles.primary} type="button" onClick={() => setOpen((value) => !value)}>{open ? "Close" : "Add Joint"}</button></div></div>
    {message ? <div className={message.includes("saved") ? styles.onTrack : styles.message}>{message}</div> : null}
    {open ? <div id="joint-inspection-form" className={styles.jointForm}><div className={styles.dimensionRule}>Each joint remains linked to its controlled specification, measurements, indications, and final decision.</div><div className={styles.formGrid}>
      <label><span>Rack</span><select value={form.rackId} onChange={(e) => update({ rackId: e.target.value })}><option value="">Select rack</option>{racks.map((rack) => <option key={rack.id} value={rack.id}>Rack {rack.rack_number} / {rack.rack_name || "Unnamed"}</option>)}</select></label>
      <label className={styles.wide}><span>Controlled Tubular Specification</span><select value={form.specId} onChange={(e) => update({ specId: e.target.value })}><option value="">Select size / weight / grade / connection</option>{specs.map((spec) => <option key={spec.id} value={spec.id}>{spec.pipe_size} / {spec.weight_ppf} #/ft / {spec.grade} / {spec.connection}</option>)}</select></label>
      <label><span>Joint ID</span><input value={form.jointId} onChange={(e) => update({ jointId: e.target.value })} /></label><label><span>Serial Number</span><input value={form.serialNumber} onChange={(e) => update({ serialNumber: e.target.value })} /></label>
      <label><span>Wall Acceptance Basis</span><select value={form.wallBasis} onChange={(e) => update({ wallBasis: e.target.value, utLowestWallInches: e.target.value === "Not Required" ? "" : form.utLowestWallInches })}><option>Premium</option><option>Class 2</option><option>Not Required</option></select></label>{form.wallBasis !== "Not Required" ? <label><span>Lowest UT Wall (in)</span><input type="number" min="0" step="0.0001" value={form.utLowestWallInches} onChange={(e) => update({ utLowestWallInches: e.target.value })} /></label> : null}
      <label><span>Visual</span><select value={form.visualResult} onChange={(e) => update({ visualResult: e.target.value })}><option>Pass</option><option>Indication</option></select></label><label><span>EMI</span><select value={form.emiResult} onChange={(e) => update({ emiResult: e.target.value })}><option>Pass</option><option>Indication</option><option>Not Required</option></select></label>{form.emiResult === "Indication" ? <label className={styles.wide}><span>EMI Indication Description / Location</span><input value={form.emiIndicationDescription} onChange={(e) => update({ emiIndicationDescription: e.target.value })} /></label> : null}
      <label><span>MPI Slip / Upset</span><select value={form.mpiResult} onChange={(e) => update({ mpiResult: e.target.value })}><option>Pass</option><option>Indication</option><option>Not Required</option></select></label><label><span>Connection Inspection</span><select value={form.connectionResult} onChange={(e) => update({ connectionResult: e.target.value })}><option>Pass</option><option>Indication</option><option>Not Required</option></select></label>
      <label className={styles.wide}><span>OMS-105 Decision for Any Indication</span><select value={form.sourceDefectDecisionId} onChange={(e) => update({ sourceDefectDecisionId: e.target.value })}><option value="">No linked defect decision</option>{decisions.map((item) => <option key={item.id} value={item.id}>{item.decision_number} / {item.joint_ids} / {item.defect_type} / {item.disposition}</option>)}</select></label>
      <label className={styles.wide}><span>Decision Justification</span><textarea value={form.decisionJustification} onChange={(e) => update({ decisionJustification: e.target.value })} /></label><label><span>Inspector</span><input value={form.inspectorName} onChange={(e) => update({ inspectorName: e.target.value })} /></label><label><span>Inspected At</span><input type="datetime-local" value={form.inspectedAt} onChange={(e) => update({ inspectedAt: e.target.value })} /></label><label className={styles.wide}><span>Notes</span><input value={form.notes} onChange={(e) => update({ notes: e.target.value })} /></label>
    </div><div className={styles.dimensionActions}><span>Required scope evidence and UT limits are evaluated automatically.</span><button className={styles.primary} type="button" onClick={() => void save()} disabled={saving}>{saving ? "Evaluating..." : "Save Joint & Add Next"}</button></div></div> : null}
    <div className={styles.jointList}>{records.map((item) => <article key={item.id} data-status={item.record_status}><div><span>{item.inspection_number}</span><strong>Joint {item.joint_id}{item.serial_number ? ` / S/N ${item.serial_number}` : ""}</strong><small>{item.inspector_name}</small></div><div><span>UT</span><strong>{item.ut_result}{item.ut_lowest_wall_inches === null ? "" : ` / ${item.ut_lowest_wall_inches} in`}</strong><small>{item.ut_minimum_inches === null ? item.wall_basis : `Minimum ${item.ut_minimum_inches} in`}</small></div><div><span>Evidence</span><strong>EMI {item.emi_result} / Dim {item.dimensional_evidence_count}</strong><small>Visual {item.visual_result} / MPI {item.mpi_result} / Connection {item.connection_result}</small></div><div><span>Disposition</span><strong>{item.final_disposition}</strong><small>{item.decision_justification}</small></div><b>{item.record_status}</b><button type="button" onClick={() => edit(item)}>Edit</button></article>)}</div>
    {!records.length ? <div className={styles.empty}>No traceable joint inspection records for this run.</div> : null}
  </section>;
}
